### ISSUE TITLE
How to add a SelectListener to the event list?

### ISSUE THREAD

**Issue by VirtueDnS** [SundeepK/CompactCalendarView#100]
--

**Comment by SundeepK** [comment]
Hi can you give a little more info on what you need? You can add a listener for when the calendar scrolls a month or when a day is selected as follows: 

```java
  // define a listener to receive callbacks when certain events happen.
        compactCalendarView.setListener(new CompactCalendarView.CompactCalendarViewListener() {
            @Override
            public void onDayClick(Date dateClicked) {
                List<Event> events = compactCalendarView.getEvents(dateClicked);
                Log.d(TAG, "Day was clicked: " + dateClicked + " with events " + events);
            }

            @Override
            public void onMonthScroll(Date firstDayOfNewMonth) {
                Log.d(TAG, "Month was scrolled to: " + firstDayOfNewMonth);
            }
        });
```

**Comment by VirtueDnS** [comment]
I want to add the selectedlistener to the event items(the message location) which are below the calendar.

**Comment by SundeepK** [comment]
Do you mean that you have a listview below the calendar view and you want to update that listview when ever a someone selects a day with its events?

**Comment by VirtueDnS** [comment]
Yes, thx

**Comment by SundeepK** [comment]
There is an example in the sample app, it does exactly this: https://github.com/SundeepK/CompactCalendarView/blob/master/sample/src/main/java/sundeepk/github/com/sample/CompactCalendarTab.java#L80

The idea is you want to set a listener:

```java
 compactCalendarView.setListener(new CompactCalendarView.CompactCalendarViewListener() {
            @Override
            public void onDayClick(Date dateClicked) {
                // get events for specific day
                List<Event> events = compactCalendarView.getEvents(dateClicked);
                eventsList.clear();
                eventsList.addAll(events)
                eventsAdapter.notifyDataSetChanged();
                }
            }

            @Override
            public void onMonthScroll(Date firstDayOfNewMonth) {
            }
        });
```

The above assumes to already have an adapter setup which takes an `Arraylist` called `eventsList`. When a day is selected, simply call `getEvents` with that date to get the events and then updates your adapter with the events and then call `notifyDataSetChanged`.

**Comment by SundeepK** [comment]
Going to assume this issue is solved, please reopen if you have more questions.
