### ISSUE TITLE
How to swipe up to collapse & swipe down to expand.

### ISSUE THREAD

**Issue by jasean** [SundeepK/CompactCalendarView#101]
How to swipe up to collapse(only show the title and the line where current day locate;to put it another way,is weekly calendar) & swipe down to expand fully!!

**Comment by SundeepK** [comment]
Hi this is has already been requested in #66. I started some basic code for this but started working on other issues since more people wanted those features than this. But I will be trying my best to work on this soon! You can track the already raised issue by watching it.

**Comment by jasean** [comment]
thanks & fighting!
