### ISSUE TITLE
Set background color in several days

### ISSUE THREAD

**Issue by JuanchoParedes** [SundeepK/CompactCalendarView#102]
Hello, it is a pleasure to me to use this library. I am a rookie developer, and I was wondering if there is a way to modify it to set a background color to several days, if there are events in them. For example, there are three days where there is one event in each one, and each day has a colored background.

Thanks for you time.

**Comment by SundeepK** [comment]
Hi, I have been recently working on this feature and I if I understand your requirement correctly have a look at issue #80. It is also most done. Please have a look, I will close this issue for now then as a result.
