### ISSUE TITLE
how to add day view, week view to the calender

### ISSUE THREAD

**Issue by KiranTarafderGitHub** [SundeepK/CompactCalendarView#103]
i want a day view which shows events for that particular day and a week view which shows only those seven days........i can be changed to normal month view just like in google calender

**Comment by SundeepK** [comment]
There is issue #66 already raised for making the calendar collapsable. I will work on that soon. If you want a day view, you can simply use some listview/recyclerview. It should be very simple todo. You just query the calendar for events and then update your Recylerview with the appropriate data.
