### ISSUE TITLE
Want different events on differet months

### ISSUE THREAD

**Issue by patelkathan** [SundeepK/CompactCalendarView#107]
How to add separate events on seperate month please help me out

**Comment by XxGoliathusxX** [comment]
compactCalendarView.addEvent(new Event(COLOR, DATEA.getTime()));
 compactCalendarView.addEvent(new Event(COLOR, DATEB.getTime()));

**Comment by kathan565** [comment]
But I want different events on January and other events in Another month and i am new to calendar activity so please explain in details..
Thanks

**Comment by kiokkio** [comment]
add.event is deprecated

**Comment by SundeepK** [comment]
Hi sorry I've been away for over a week and I'm catching up with my updates. You can use the method `addEvent(Event event, boolean shouldInvalidate)` todo what you want:

```
Event ev2 = new Event(Color.GREEN, 1433704251000L);
compactCalendar.addEvent(ev2, true);
```

I would suggest using the method `addEvents` because it takes a list so you can add events in a single method call.

**Comment by syafiqzahir** [comment]
thanks admin very much appereciated !
