### ISSUE TITLE
CompactCalendarView.CompactCalendarViewListener is required?

### ISSUE THREAD

**Issue by joaozitopolo** [SundeepK/CompactCalendarView#11]
On sample, the listener is informed, but on documentation isn't informed to be required.

If not informed, occur an NPE on month events:

    public void showNextMonth() {
        this.compactCalendarController.showNextMonth();
        this.invalidate();
        this.listener.onMonthScroll(this.compactCalendarController.getFirstDayOfCurrentMonth());
    }

I suggest a null test for this.listener

**Comment by SundeepK** [comment]
Ah that was a recent change I made the other day :(. I'll fix that today. Unfortunate , that class isn't tested since it forwards on calls to the class which actually does the processing.

**Comment by SundeepK** [comment]
Just need to release today.

**Comment by SundeepK** [comment]
Now available in:
```
dependencies {
    compile 'com.github.sundeepk:compact-calendar-view:1.7.2'
}
```
