### ISSUE TITLE
FirstDayofCurrentMonth 

### ISSUE THREAD

**Issue by kallem439** [SundeepK/CompactCalendarView#112]
Hi Sundeep,

I dont want focus for first day of  month. When i am scrolling to next month by default first day of the month in focus..

I am unable to find that ? Can you please help me out ???

**Comment by XxGoliathusxX** [comment]
onmonthscroll(){setSelectedDay(...)}

**Comment by SundeepK** [comment]
Hi, there is a ticket already raised #90 for this. Will do it soon once I finish some other work I'm currently finishing off.
