### ISSUE TITLE
Tests are not working correctly on JVM configured in a different timezone

### ISSUE THREAD

**Issue by JulienArzul** [SundeepK/CompactCalendarView#115]
Hi,

The tests are not passing correctly when we launch them in a JVM set in a different timezone (Paris in my case). The default timezone must be set to be able to use arbitrary timestamps.

I can open a PullRequest to correct this if needed : 
https://github.com/JulienArzul/CompactCalendarView/tree/%40tests/jvm_config_independance
(in this branch, I also set the default locale to english and correct a Timestamp that had a wrong value)

**Comment by SundeepK** [comment]
I thanks for the issue, I think that should be set as the default since it that is my default time zone

```java
        System.out.println(tz.getDisplayName());
        System.out.println(tz.getID()); // prints Europe/London
```

So if you add:
```java
        Locale.setDefault(Locale.ENGLISH);
        TimeZone.setDefault(TimeZone.getTimeZone("Europe/London"));
```

The code should work without modification then. Let me know if this works for you.

**Comment by JulienArzul** [comment]
Yes, I've actually added this (to keep it GMT-based and not associated with a country/city) : 
```
Locale.setDefault(Locale.ENGLISH);
TimeZone.setDefault(TimeZone.getTimeZone("GMT"));
```


Beware that if you do this, there is one timestamp that stops working (probably because of the change of time in London). It's the one line 93. It now should be : 
```
//Wed, 01 Apr 2015 00:00:00 GMT
assertEquals(new Date(setTimeToMidnightAndGet(cal, 1427846400000L)), underTest.getFirstDayOfCurrentMonth());
```

**Comment by SundeepK** [comment]
Ok gotcha, we can update that test then. If you want to send just a pull request for this change I can merge it at some point. Thanks!

**Comment by SundeepK** [comment]
Closing as code as been merged.
