### ISSUE TITLE
Showing 2 months on landscape mode!!!

### ISSUE THREAD

**Issue by longnguyencmg** [SundeepK/CompactCalendarView#120]
First of all, thank you so much for your library which is excellent. Can you help me with this case, as I want to show 2 months on landscape mode like the screenshot (it's just the prototype and I want to do like this)

![screen shot 2016-10-21 at 4 23 45 pm](https://cloud.githubusercontent.com/assets/4001695/19593479/fbe9f0fe-97aa-11e6-95a6-235c8d24298c.png)

I tried to set width for the view but it did't work :(

Thank you very much!

**Comment by SundeepK** [comment]
Hi, currently the library only supports showing one month at a time. So this will be a new feature. It already draws both previous and next month but you can only see them when you scroll. So it should be possible todo this, hopefully, with little changes. But I'm not too sure without having a proper look at the code. Sorry about that.

**Comment by longnguyencmg** [comment]
Thank you, no problems, I find solution :D.

**Comment by hrataci** [comment]
Hi,is there any solutions to show ComactCalendarView in Recycler view , to show year (3x4) ?
