### ISSUE TITLE
Add compactCalendarCurrentSelectedDayTextColor attr

### ISSUE THREAD

**Issue by erva** [SundeepK/CompactCalendarView#125]
Currently lib allows configure selected_day_bg but not selected_day_text_color.

**Comment by SundeepK** [comment]
Just going though some issues and doing some cleanup. I believe this was already done some time ago, just forgot to update this issue. You can use `compactCalendarCurrentSelectedDayTextColor` to change the color.

**Comment by SyafiqTM** [comment]
Thank you mr dev sundeepk. ☺
