### ISSUE TITLE
Custom Events

### ISSUE THREAD

**Issue by derBinder** [SundeepK/CompactCalendarView#126]
Hi, i want to build a custom Event-Class, which extends your existing Event.
The class looks like this: 

```java
public class CustomEvent extends com.github.sundeepk.compactcalendarview.domain.Event{

    public CustomEvent(int color, long timeInMillis) {
        super(color, timeInMillis);
    }

    public CustomEvent(int color, long timeInMillis, Object data) {
        super(color, timeInMillis, data);
    }

    /* more fields below ...*/
}
```

I can't set the events via clanedarview.addEvents() like you see here:

```java
ArrayList<CustomEvent> events = new ArrayList<>();
events.add(new CustomEvent(Color.RED, Calendar.getInstance().getTimeInMillis()));
events.add(new CustomEvent(Color.GREEN, Calendar.getInstance().getTimeInMillis()));
calendarView.addEvents(events);
```

I can set one event at a time via calendarView.addEvent(event) (this works somehow).
When I try to get the events using calendarView.getEvents(), I get an error that tells me, the types are incompatible.

```java
 List<CustomEvent> events = calendarView.getEvents(Calendar.getInstance().getTimeInMillis());
```

Can you please help me to get this working?
Thank you :)

**Comment by SundeepK** [comment]
Hi, I'll have a look through the code you give you a hand when I get the time today. Is there are reason for extending the class?

**Comment by SundeepK** [comment]
Hi can you share any errors you are getting over here please?

**Comment by derBinder** [comment]
Hi, thanks for your fast response.
I want to add an owner / owner-id to the event, thats why I want to extend the class.

The error I get when I try to use ```addEvents()```:
```
addEvents
(java.util.List<com.github.sundeepk.compactcalendarview.domain.Event>)
in CompactCalendarView cannot be applied to
(java.util.ArrayList<de.fb.teamcalendar.data.CustomEvent>)
```
The error I get when I try to use ```getEvents()``` (without casting):
```
Incompatible types.
Required:
java.util.List <de.fb.teamcalendar.data.CustomEvent>
Found:
java.util.List <com.github.sundeepk.compactcalendarview.domain.Event>
```
When I cast to List<CustomEvent> I get:
```
Inconvertible types; 
cannot cast 
'java.util.List<com.github.sundeepk.compactcalendarview.domain.Event>' 
to 
'java.util.List<de.fb.teamcalendar.data.CustomEvent>'
```

**Comment by SundeepK** [comment]
@derBinder Ah i think I understand. Why don't you use the custome object parameter?

```
Event e = new Event(Color.GREEN, Calendar.getInstance().getTimeInMillis(), new Owner("someId"))
```

Then you can get the object out:

```
Owner owner = (Owner) e.getData();
```

**Comment by derBinder** [comment]
I dont know why I didn't use that parameter, maybe i just didn't see it lol.
Your example works well.
Thank you so much for your fast response. :)
