### ISSUE TITLE
sync events

### ISSUE THREAD

**Issue by gokul1408** [SundeepK/CompactCalendarView#128]
hey sundeep, how to sync events with google calendar

**Comment by RatHN** [comment]
Uhhhh bro... uuuhh bro....! What you are asking for is not to be answered here. These is not an issue about the CompactCalendarView, nor a simple help request.
I recommend you to read the [Calendar Provider API guide](https://developer.android.com/guide/topics/providers/calendar-provider.html) and be careful not to mess with the API `Events` and the CompactCalendar `Events`.

**Comment by SundeepK** [comment]
As @RatHN this is probably out of scope of this library as it is used to only display a UI calendar. Syncing this with google calendars is something you will have to handle by your self for now.
