### ISSUE TITLE
hello! . I want to add some text on date control Can it achieve?thanks

### ISSUE THREAD

**Issue by godmarvin** [SundeepK/CompactCalendarView#131]
[
![h 4yyf8 iyr 2 hvgx m0](https://cloud.githubusercontent.com/assets/7519968/20880224/038afe54-bb12-11e6-8e92-346b7c779de8.png)
](url)

**Comment by SundeepK** [comment]
Hi i believe this is very similar to #77 . I'm going to close this as duplicate and continue disccussion on that issue.
