### ISSUE TITLE
Setting the color of the event indicator based on the number of events on that day

### ISSUE THREAD

**Issue by laa413** [SundeepK/CompactCalendarView#133]
I am working on a project that needs a calendar, and I stumbled upon your source code which seemed to match closely with what I needed.  It looks great by the way.  I have a question, though: 
Am I able to set the color of each day's event indicator to a specific color or does it all have to be one color?  In my application, I am trying to implement a UI where the color of the event indicator depends on the number of events that day so as to make it easier to see when the user has a full schedule. for instance, if I was very busy on one day it would be red, and maybe on another day I would only be somewhat busy and it would show yellow, and if I was mostly free it would be green.  If this is not possible is there any other way that it could be done?
This is a screenshot of what I am aiming for, and thank you for your help!
![screen shot 2016-12-11 at 2 10 47 am](https://cloud.githubusercontent.com/assets/10834883/21078723/18474332-bf47-11e6-89f1-48d576a9cd1d.png)

**Comment by SundeepK** [comment]
```java

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        final CompactCalendarView compactCalendarView = (CompactCalendarView) findViewById(R.id.compactcalendar_view);

        // Add event 1 on Sun, 07 Jun 2015 18:20:51 GMT
        Event ev1 new Event(Color.GREEN, 1433701251000L, "Some extra data that I want to store.");
        compactCalendar.addEvent(ev1);

```

Each event takes in any color value. Check the sample app and the readme for more details.

**Comment by laa413** [comment]
Thank you for the explanation.
