### ISSUE TITLE
[Question] Event list not showing on initialization if current date have events.

### ISSUE THREAD

**Issue by khalid-mahmood** [SundeepK/CompactCalendarView#134]
how to show events list too if current date have events on calendar start.?
if click on current date after select another date it shows.

**Comment by SundeepK** [comment]
Hi can you add some basic code of what you are currently doing? Thanks.

**Comment by khalid-mahmood** [comment]
i am just using sample code..
in sample code there is events for 6th of month.. if you change current date to 6 then restart app you won't see a list of events below in sample..
if you select other day and then select again it will show list.

**Comment by khalid-mahmood** [comment]
just call  notifydatasetchanged() after adding event to list and adapter initialization.
