### ISSUE TITLE
how to set a time as select time  and then update Calender  view to select mode

### ISSUE THREAD

**Issue by carl1990** [SundeepK/CompactCalendarView#135]
I know in calender when click one day can get this day and update this view to select mode by

	customerCalenderView.setListener(new CompactCalendarView.CompactCalendarViewListener() {
            @Override
            public void onDayClick(Date dateClicked) {
                
            }

            @Override
            public void onMonthScroll(Date firstDayOfNewMonth) {
            
        });
        
but how can set a day as selected day and update view to selected mode not by click

**Comment by khalid-mahmood** [comment]
try {
            compactCalendarView.setCurrentDate(new SimpleDateFormat("yyyy-MM-dd").parse("2016-12-19"));
        }catch (ParseException e){
           //TODO handle on exception
        }

**Comment by carl1990** [comment]
@khalid-mahmood  thank you ! is work well

**Comment by SundeepK** [comment]
Looks like the problem is solved, thanks!.
