### ISSUE TITLE
how to show event on CompactCalendarView with a simple dot on particular date

### ISSUE THREAD

**Issue by hsehsiv** [SundeepK/CompactCalendarView#140]
please help me out

**Comment by JonnyCiel** [comment]
You will have to have the time in milliseconds for that particular date you want to add the dot (event).

Once you have that time in milliseconds, you then create a List of Events (List<Events>) and in that list you add your event like this, for example eventList.add(new Event(Color.RED, timeinmilliseconds, Object)). Once you have a list of events, you can proceed to add the dots (events) into the calendar using for example, calendarView.addEvents(eventList);

**Comment by SundeepK** [comment]
Closing issue, please re-open if you need more help.
