### ISSUE TITLE
Rather than an Issue, Would like to ask how to break down the items from an Event

### ISSUE THREAD

**Issue by StudentProgrammer23** [SundeepK/CompactCalendarView#141]
I just recently picked up SundeepK calendar library and have so far created a scheduler program using PHP as my backend. The program fetches the events from an online database and i add them to the Compact Calendar by using this code:

for (int i = 0; i < arrayList.size(); i++) {
                        Item item = arrayList.get(i);
                        Event[] evTemp = new Event[arrayList.size()];
                        evTemp[i] = new Event(Color.RED, Long.parseLong(item.getDt()),item.getTitle());
                        compactCalendar.addEvent(evTemp[i]);
                    }

I know its messy, i used an Item Class since its the method i am familiar with. 

Here comes the problem,  This is my patch of code for onClick. I would like to get only the timeinMillis to be shown if the List is not empty. the code on my else shows color, timeinMillis and data.

@Override
            public void onDayClick(Date dateClicked) {
                List<Event> events = compactCalendar.getEvents(dateClicked);

                if (events.isEmpty()) {
                    Toast.makeText(Calendar_form.this, "No events for: " + dateClicked, Toast.LENGTH_SHORT).show();
                } else {
                    Toast.makeText(Calendar_form.this, "Day was clicked: " + dateClicked + " with events " + events, Toast.LENGTH_SHORT).show();
                }
            }

Thank you in advance.

**Comment by JonnyCiel** [comment]
Hello. 

Please try this

```
for (Event eventsMillis: events) {
                                    Toast.makeText(AmbientesDetailActivity.this, "millis" + booking.getTimeInMillis(), Toast.LENGTH_SHORT).show();
```

**Comment by StudentProgrammer23** [comment]
Thank you very much! it worked perfectly :)
