### ISSUE TITLE
how to get selected date On CompactCalanderView in ontouch listener

### ISSUE THREAD

**Issue by hsehsiv** [SundeepK/CompactCalendarView#142]
I am trying to get the date on which I click so to pass it to another activity to show the details of that event so please help me out of this issue ...... this is my code  ( on touch listener)

  
       compactCalendar.setOnTouchListener(new View.OnTouchListener() {

            @Override
            public boolean onTouch(View v, MotionEvent event) {
                if (event.getAction() == MotionEvent.ACTION_DOWN)
                {
                    Log.e("TouchListner","Compacttouchlistner clicked");
                    startActivity(new Intent(getApplicationContext(), EventsListActivity.class));
                    Log.e("ID   ",  id);
                    compactCalendar.shouldDrawIndicatorsBelowSelectedDays(true);

                    return true;
                }
                return false;
            }
        });

**Comment by SundeepK** [comment]
Hi sorry for the delayed reply, holiday season has made me busy. But this is very easy todo:

```java
        compactCalendarView.setListener(new CompactCalendarView.CompactCalendarViewListener() {
            @Override
            public void onDayClick(Date dateClicked) {
                List<Event> events = compactCalendarView.getEvents(dateClicked);
                Log.d(TAG, "Day was clicked: " + dateClicked + " with events " + events);
            }

            @Override
            public void onMonthScroll(Date firstDayOfNewMonth) {
                Log.d(TAG, "Month was scrolled to: " + firstDayOfNewMonth);
            }
        });
```

Use the set listener method to register a listener for onclick events. There is more on this on the example app and readme.

**Comment by SundeepK** [comment]
Please let me know if there are any more question. Closing this issue for now.
