### ISSUE TITLE
cannot select current day

### ISSUE THREAD

**Issue by gaultierq** [SundeepK/CompactCalendarView#143]
I cannot select the current day. 
The DayCircleIndicator are drawn in priority for the currentDay instead of the currentSelectedDay. 

Don't you think the selected day should prevail ?

**Comment by SundeepK** [comment]
This one is debatable, the library follows exactly what google has done. Google calendars will colour today as blue for example and when you select it, It will still show blue. Instead of the currently selected day color of grey. That is not to say Google is wrong, its just a different design choice.

**Comment by gaultierq** [comment]
Yes they do indeed. 
But the purpose of the google calendar is just to "goto" another date. So, when the user click on today's date, he has the same feedback than for the other dates: the calendar is closing and the navigation performed.

My usage is using the calendar as a date picker, and ideally the user should be able to pick today's date as any other date. With today's version the user can select today's date, but then he doesn't have the same visual feedback: he needs to check the written date to be sure he selected the right date. I think this could be improved. 
What do you think ?

**Comment by gaultierq** [comment]
btw I think [this PR](https://github.com/SundeepK/CompactCalendarView/pull/56) is related to my issue

**Comment by SundeepK** [comment]
Valid points, I'll see if I can do this in the up coming week. Shouldn't be too difficult I think.

**Comment by gaultierq** [comment]
Do you still considering implementing it ?

**Comment by SundeepK** [comment]
Yes I'll get around to it soon. I'm currently working on another issue which seems a few people would like.

**Comment by gaultierq** [comment]
great thanks !

**Comment by SundeepK** [comment]
Should be in below version. Please allow some time for it to be available.
```
dependencies {
    compile 'com.github.sundeepk:compact-calendar-view:1.9.9'
}
```

**Comment by gaultierq** [comment]
working as expected 
great job ! thanks
