### ISSUE TITLE
SOLVED Issue: Cannot change current day background color in java

### ISSUE THREAD

**Issue by ngrova** [SundeepK/CompactCalendarView#147]
I am trying to get the current day to change background color depending on if the current day has an event or not.  Has anyone had success being able to visually display that the current day has an event?

**Comment by ngrova** [comment]
I believe I figured out how to edit the file you have uploaded on this site to have the calendar only fill in the current day if no events are present (at the start of the day to give an exact reference time, as my app will always use the start of the day for event times).  I am confused how to use this change in my app.  I tried pushing a version to this repository, and also tried creating my own repository that is a copy of this one.  Sorry for being a newbie, but i'm a bit confused on how to take this calendar and make changes then use those changes in my program/app.

**Comment by ngrova** [comment]
I have solved my own issue.  I was trying to change the background color based on an if statement that had an error.  This is solved, and thanks to this repository I have a great calendar!  Thanks to all!

**Comment by SundeepK** [comment]
Sorry for not replying but I have been immensely busy. Glad too see the problem is fixed.

**Comment by sjla** [comment]
@ngrova i am facing the same issue. I want to show current date as all other dates( if current day does not have event )and if current day has event it should be show as other eventindicator.but current date background color is not working if current day has event.
