### ISSUE TITLE
how to give square box background to the dates layout

### ISSUE THREAD

**Issue by KiranTarafderGitHub** [SundeepK/CompactCalendarView#148]
![cc](https://cloud.githubusercontent.com/assets/21355283/21608524/081253f4-d1e3-11e6-9d92-7607f7615c74.png)

**Comment by SundeepK** [comment]
This is very much different to how google calendar works (which this library aims to follow). You can however easily take a fork the library and change it to display squares instead. If you need help on exactly how to-do this, I can explain it. There is some drawing code to display circles, simply replace that to display a Rect instead and I think that would the first place to start.

**Comment by KiranTarafderGitHub** [comment]
Thanks for d tip.... And i have done exactly what u have said... And
succeeded to... U can close dis issue as enhancement!!!!!
