### ISSUE TITLE
Deactivate month scroll

### ISSUE THREAD

**Issue by javo0112** [SundeepK/CompactCalendarView#15]
hi again Sundeepk

My app is almost done, but i am having some troubles again with my pager and the calendar,
is there a way to deactivate the month scroll so it doesn't interfiere with the tab pager?

**Comment by SundeepK** [comment]
I'll have to look at this when I get back from holiday. Probably another week. You can have a go if you want to send a pull request to get the functionality done sooner but it won't get merged till I gte back :(

**Comment by SundeepK** [comment]
No available in com.github.sundeepk:compact-calendar-view:1.7.3

**Comment by SundeepK** [comment]
Added  shouldScrollMonth(boolean shouldDisableScroll) method.

**Comment by javo0112** [comment]
great, just wanted to let you know my app (school calendar for a private institute) is now available in the google play store and your calendar looks great on it and it's one of the main features,  thanks! 

https://play.google.com/store/apps/details?id=com.voidapps.repmex

**Comment by SundeepK** [comment]
Well done! The app looks very professional and well designed. :)
