### ISSUE TITLE
How to open specific month calendar ?

### ISSUE THREAD

**Issue by aamirmsw** [SundeepK/CompactCalendarView#151]

**Comment by SundeepK** [comment]
Hi, you mean you want to show a speific month? You can use the `setCurrentDate()` which takes a Date object. Simply get a date set to the desired month and use that method to display that month.

**Comment by aamirmsw** [comment]
Could you please elaborate ?

**Comment by SundeepK** [comment]
Below is an example using milliseconds. But you can create a `Calendar` object and set the month, year and day accordingly. Then use the `getTime` method on the `Calendar` object to get the date. There are many example on how todo this.
```java
  // ... code omitted for brevity         
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        final CompactCalendarView compactCalendarView = (CompactCalendarView) findViewById(R.id.compactcalendar_view);
        //GMT: Sun, 07 Jun 2015 19:10:51 GMT
        compactCalendarView.setCurrentDate(new Date(1433704251000L));
        // calendar will now show Jun 2015 month
    } 
```

**Comment by SundeepK** [comment]
Please reopen if you have any more qestions.

**Comment by TheIronLord** [comment]
It changes the year
