### ISSUE TITLE
Cant add event from function onActivityResult

### ISSUE THREAD

**Issue by ranzo1** [SundeepK/CompactCalendarView#152]
If i add event in function on create,it works,but if i want to add event from function onActivityResult,dont work...Can you help,if you have some example on this,i will be thankful!

**Comment by SundeepK** [comment]
Can you show some code examples? I don't see why this should not work as long as you have a reference to a CompactCalendarView instance. I will also try testing this out then.

**Comment by ranzo1** [comment]
Thanks for answer, just try that, if you can do example and show it,  and if it works i will be able to do that in my app. It seems very simple but dont work for me...

**Comment by SundeepK** [comment]
Are you sure your `onActivityResult` is being called? Can you put some logging to see that it is being executed?

**Comment by SundeepK** [comment]
Here is how I started the activity:

```java
                compactCalendarView.removeAllEvents();
                Intent myIntent = new Intent(getActivity(), TestActivity.class);
                startActivityForResult(myIntent, 100);
```


```java
public class TestActivity extends Activity {


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.test_activity);
    }

}
```
Then in my fragment:
```java
    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        Log.d(TAG, "on activity result");
        loadEvents();
        loadEventsForYear(2018);
    }
```

**Comment by ranzo1** [comment]
`public` class EventsActivity extends AppCompatActivity {
 private CompactCalendarView compactCalendar;
 private Event ev1;
 public static List<Event> list_of_events =new ArrayList<>();

 protected void onCreate(Bundle savedInstanceState) {

 compactCalendar = (CompactCalendarView) findViewById(R.id.compactcalendar_view);
 compactCalendar.setUseThreeLetterAbbreviation(true);
        
//list_of_events.add(ev3);
//compactCalendar.addEvents(list_of_events);



 @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {

        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == 2) {

            try {

                if (data.getStringArrayListExtra("1234") != null) {

             //i just tested this,and when this activity recive data,dont  insert event from activityResult function
                   ev1 = new Event(Color.MAGENTA,1477040400000L,"Event");


                    list_of_dates.add(ev3);
                    compactCalendar.addEvents(list_of_dates);

     }


            } catch (Exception e) {
                Log.i("", e.getMessage());

            }



``

**Comment by ranzo1** [comment]
onActivityResult function works,tested on textView,but dont work for calendar...

**Comment by SundeepK** [comment]
Closing issue as it is resolved.
