### ISSUE TITLE
Can we add recurrent date for events (i.e Public Holiday) for each year?

### ISSUE THREAD

**Issue by syafiqzahir** [SundeepK/CompactCalendarView#153]
-Edit- 

I just found my answer recently . thanks master SundeepK

private void loadPublicHoliday() throws ParseException {

        String date="01/01/2017"; // new year
        String date2 = "28/01/2017"; // chinese new year
        String date3 = "29/01/2017"; // chinese new year
        String date4 = "01/05/2017"; // labour day
        String date5 = "10/05/2017"; // wesak
        String date6 = "31/8/2017"; // national day
        String date7 = "1/9/2017"; // Hari Raya Haji
        String date8 = "16/9/2017"; //Malaysia Day
        String date9 = "25/12/2017"; //Christmas

        String [] dateHoliday = {date,date2,date3,date4,date5,date6,date7,date8,date9};

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        Calendar c[]= new Calendar[dateHoliday.length];

        for(int i=0 ; i<dateHoliday.length; i++)
        {
            c[i] = Calendar.getInstance();
            c[i].setTime(sdf.parse(dateHoliday[i]));
        }

        for(int co=0; co<2; co++){ // 0 = 2017

            Event event = new Event(getResources().getColor(R.color.black),c[0].getTimeInMillis(), "New Year");
            compactCalendarView.addEvent(event, true);

            Event event2 = new Event(getResources().getColor(R.color.black),c[1].getTimeInMillis(), "Chinese New Year");
            compactCalendarView.addEvent(event2, true);

            Event event3 = new Event(getResources().getColor(R.color.black),c[2].getTimeInMillis(), "Chinese New Year");
            compactCalendarView.addEvent(event3, true);

            Event event4 = new Event(getResources().getColor(R.color.black),c[3].getTimeInMillis(), "Labour Day");
            compactCalendarView.addEvent(event4, true);

            Event event5 = new Event(getResources().getColor(R.color.black),c[4].getTimeInMillis(), "Wesak");
            compactCalendarView.addEvent(event5, true);

            Event event6 = new Event(getResources().getColor(R.color.black),c[5].getTimeInMillis(), "National Day");
            compactCalendarView.addEvent(event6, true);

            Event event7 = new Event(getResources().getColor(R.color.black),c[6].getTimeInMillis(), "Hari Raya Haji");
            compactCalendarView.addEvent(event7, true);

            Event event8 = new Event(getResources().getColor(R.color.black),c[7].getTimeInMillis(), "Malaysia Day");
            compactCalendarView.addEvent(event8, true);

            Event event9 = new Event(getResources().getColor(R.color.black),c[8].getTimeInMillis(), "Christmas");
            compactCalendarView.addEvent(event9, true);

            for(int m=0; m<dateHoliday.length; m++)
            {
                c[m].add(Calendar.YEAR, 1);
            }
        }
    }

**Comment by SundeepK** [comment]
Well done for finding the solution.

**Comment by lucasrafagnin** [comment]
Hi @SundeepK,
I dont understand, 
I have a calendar for organizing birthdays and I would like the event to be replicated every year on the calendar. Is it possible to do that?

**Comment by SundeepK** [comment]
@lucasrafagnin Yep should be simple. Just perform a loop for every year you want to add an event and use the Java calendar class to set the year each time for that specific date. Then add an event for each yeah calling getTime on the calendar instance. You can do this for the next/previous 50 years for example and it will add 100 recurring events. Then you can add more when the user scrolls 50 yrs in the future/past.

Below will add an event every year for the next 50 years.
```java
Calendar calendar = Calendar.getInstance();
calendar.setTime(new Date()); // Add the specific date you want
List<Event> events = new ArrayList<>();
for(int i=0 ; i < 50 ; ++i)
    {
        calendar.add(Calendar.YEAR, i);
        events.add(new Event(Color.GREEN, calendar.getTimeInMillis(), "Birthday"));
    }
compactCalendar.addEvents(events);
```

**Comment by lucasrafagnin** [comment]
Thank you @SundeepK !
