### ISSUE TITLE
Get events on create

### ISSUE THREAD

**Issue by BartlomiejRasztabiga** [SundeepK/CompactCalendarView#155]
Hi.
I would like to know how to get events on actual day on calendar startup. I tried getting events on actual Date but it doesn't work even if I pass the same amount of miliseconds and I don't know why. Could you help me?

**Comment by SundeepK** [comment]
Do you have any example code you are trying? All events are stored in memory and are specific to one instance of the calendar. If you create events, it will only show for the current calendar instance.

On calendar startup, there will be no events until you add them each and everytime, just like a new List or a Map. Once you add them you can query for them but only for the life time of the object.

**Comment by BartlomiejRasztabiga** [comment]
Nevermind, I was querying event without waiting for the AsyncTask, that loads them into the calendar, to finish. I've already fixed it, thank you 👍
