### ISSUE TITLE
Multiple event indicators not showing up

### ISSUE THREAD

**Issue by preyesm** [SundeepK/CompactCalendarView#156]
Hi @SundeepK the library is too awesome. I just added the dependency of the library version 1.9.7 and used calendar view in xml. Created new events and added them to the calendarView. event indicators are maintained same as large_fill and small_fill but the dots do not show up under the dates. Any idea of what needs to be changed?

**Comment by SundeepK** [comment]
Hi @preyesm can you show me your xml layout for the calendar?

**Comment by preyesm** [comment]
Hey Sundeep, greetings for the day. PF below the xml of your calendar
<com.github.sundeepk.compactcalendarview.CompactCalendarView xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/compactCalendarView"
    android:layout_width="match_parent"
    android:layout_height="250dp"
    android:layout_alignParentTop="true"
    android:paddingLeft="10dp"
    android:paddingRight="10dp"
    app:compactCalendarBackgroundColor="@color/white"
    app:compactCalendarCurrentDayBackgroundColor="@color/dark_blue"
    app:compactCalendarCurrentSelectedDayBackgroundColor="#E57373"
    app:compactCalendarTargetHeight="250dp"
    app:compactCalendarTextColor="@color/black"
    app:compactCalendarCurrentDayIndicatorStyle="fill_large_indicator"
    app:compactCalendarEventIndicatorStyle="small_indicator"
    app:compactCalendarOtherMonthDaysTextColor="@color/light_grey"
    app:compactCalendarMultiEventIndicatorColor="@color/green"
    app:compactCalendarCurrentSelectedDayIndicatorStyle="fill_large_indicator"
    app:compactCalendarTextSize="12sp" />

**Comment by SundeepK** [comment]
I don't see any thing wrong with the layout. How are you adding the events? The sample in the repo should have some good examples on how to do this.

**Comment by preyesm** [comment]
I just populate objects of Event class and do compactCalendarView.addEvents(events). 
Event event = new Event(Color.parseColor("#479ade"), futureReminders.get(i).getReminderTime(), futureReminders.get(i));
            events.add(event);
binding.compactCalendarView.addEvents(events);

**Comment by SundeepK** [comment]
Is `futureReminders.get(i).getReminderTime()` in miliseconds?

**Comment by preyesm** [comment]
getReminderTime is a variable of type Long containing epoch time

**Comment by SundeepK** [comment]
The library requires that the time is in miliseconds, epoch time can be in seconds so if it's in seconds multiply by 1000 to get milis and try that.

**Comment by preyesm** [comment]
yeah.. will try and let you know

**Comment by preyesm** [comment]
hey @SundeepK it has worked.. *1000.. thanks for the help
app:compactCalendarTargetHeight="250dp"
                app:compactCalendarTextColor="@color/black"
                app:compactCalendarBackgroundColor="@color/white"
                app:compactCalendarCurrentDayBackgroundColor="@color/dark_blue"
                app:compactCalendarCurrentDayIndicatorStyle="fill_large_indicator"
                app:compactCalendarEventIndicatorStyle="small_indicator"
                app:compactCalendarMultiEventIndicatorColor="@color/green"
                app:compactCalendarTextSize="12sp" />
For multi events how do i acheive "two dots+" from the xml

**Comment by SundeepK** [comment]
For the plus you need to have more 3 or events in one day.

**Comment by SundeepK** [comment]
Please re-open if you have any more questions.

**Comment by preyesm** [comment]
Sure , thanks :)
