### ISSUE TITLE
one dot if a date has an event, regardless of the number of events

### ISSUE THREAD

**Issue by MitchDroid** [SundeepK/CompactCalendarView#159]
Hi @SundeepK , it's possible only be one dot if a date has an event, regardless of the number of events?

Thanks for your time!

**Comment by MitchDroid** [comment]
@SundeepK

**Comment by SundeepK** [comment]
Hi @MitchDroid have a look at issue #154. That issue is very similar to this.

**Comment by MitchDroid** [comment]
Perfect @SundeepK , That works!... thank  you for your time!

Cheers
