### ISSUE TITLE
when i change to chinese,the day of week only show “周”

### ISSUE THREAD

**Issue by Xcent-xl** [SundeepK/CompactCalendarView#160]
when i change to chinese,the day of week only show “周”,look forward to show such as “周一”，“周二”,maybe the width is too narrow to show

**Comment by SundeepK** [comment]
Hi, can you show me the code you are using? When I print Chinese days of week, I get:

```
        DateFormatSymbols dateFormatSymbols = new DateFormatSymbols(locale);
        String[] dayNames = dateFormatSymbols.getShortWeekdays();
        Log.d("weekutils", "found day names " + Arrays.toString(dayNames));
```

```
weekutils: found day names [, 周日, 周一, 周二, 周三, 周四, 周五, 周六]
```
Is that correct days of week in china?

When I set Locale to China using:
```
                Locale locale = Locale.CHINESE;
                TimeZone timeZone = TimeZone.getTimeZone("Asia/Chungking");
                compactCalendarView.setLocale(timeZone, locale);
                compactCalendarView.setUseThreeLetterAbbreviation(true);
```

And I get:

![chineselocale](https://cloud.githubusercontent.com/assets/2339563/22397020/58012810-e55f-11e6-84a4-d85beaf7715c.png)

**Comment by SundeepK** [comment]
Did you have a try at the above?

**Comment by Xcent-xl** [comment]
your code works,you are so nice
