### ISSUE TITLE
Update library make app crash

### ISSUE THREAD

**Issue by florianhenonin** [SundeepK/CompactCalendarView#161]
I want to update library from 1.8.4 to 1.9.3 and all app is crash.
Seems like appcompat-v7:23.4.0 is not compatible with this version.

java.lang.RuntimeException: Unable to start activity ComponentInfo{package.name/package.name.activity.MainActivity}: android.view.InflateException: Binary XML file line #11: Binary XML file line #97: Error inflating class android.support.design.widget.FloatingActionButton

**Comment by SundeepK** [comment]
The support version was bumped to `compile 'com.android.support:appcompat-v7:24.2.1'` in the library. Perhaps it's best to use the lowest version possible to ensure compatability? I'll have to play around with this one.

You can eiher update the version in your app or download the code locally and change the version and add as a library project until this is investigated further.
