### ISSUE TITLE
 Calendar Multi Event Indicator Color

### ISSUE THREAD

**Issue by MitchDroid** [SundeepK/CompactCalendarView#162]
Hi @SundeepK , Is it possible to change the indicator color in code dynamically?

I did in xml
 app:compactCalendarMultiEventIndicatorColor="@color/colorAccent"

But I need to change that color in code and I can not find the correct property, something like:
mCompactCalendar.setIndicatorColor(int color).

I hope you can help me.

Cheers.

**Comment by SundeepK** [comment]
Hi, if you are talking about changing the color of the plus sign that appears when there are multiple events, then it's only possible from xml right now. I'm currently working on another issue, but I'll try and sneak this change in at the same time. I can't say when it will be done but hopefully soon.

**Comment by MitchDroid** [comment]
Hi, @SundeepK , Thanks for soon response,  I mean to the dot indicator color , I'm using just one dot  for multievents and I need to change the dot color if it is possible.

Thanks in advance!

**Comment by MitchDroid** [comment]
Hi @SundeepK, I had not seen that I could set the event dot color in Event Object color parameter.

Actually nevermind,

Thanks for your time.

**Comment by SundeepK** [comment]
Yes your right, Event object takes any color you want.
