### ISSUE TITLE
I add a new event, but there is no change to the calendar,plz why?

### ISSUE THREAD

**Issue by Faterjames** [SundeepK/CompactCalendarView#163]
Event ev1 = new Event(Color.RED,time, "Some extra data that I want to store.");
        calendar.addEvent(ev1,true);

I wrote like this, but there is no change to the calendar,(i want a little dot below the date), and i truly add event in right way that the log told me there is a event,but where is my dot !!!

plz answer my quanstion!!!

**Comment by Faterjames** [comment]
Anybody help me!plz

**Comment by SundeepK** [comment]
Hi, make sure your time is in milliseconds. So if it is in seconds then do `time * 1000`. If you are using milliseconds then I then I need to see more code to find out what might be wrong.

**Comment by Faterjames** [comment]
hello , thanks for your reply,i'm sry that i did not reply at time, i am sure i have set the milliseconds, i use toast to see that.
and here is the whole project ,i just want to finish a simple demo,but QAQ ,i hope you can read my code and solve my problems please . thank you very much!!!
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        String[] a = {"日","一","二","三","四","五","六"};
        final CompactCalendarView calendar = (CompactCalendarView) findViewById(R.id.compactcalendar_view);
        long time = System.currentTimeMillis();
        Toast.makeText(getApplicationContext(),Long.toString(time),Toast.LENGTH_SHORT).show();

        calendar.setLocale(TimeZone.getTimeZone("GMT"),Locale.CHINA);
        calendar.setFirstDayOfWeek(Calendar.SUNDAY);
        calendar.setDayColumnNames(a);
        Event ev1 = new Event(Color.RED,time, "Some extra data that I want to store.");
        calendar.addEvent(ev1,true);
        Event ev2 = new Event(Color.RED,time, "Some extra data that I want to store.");
        calendar.addEvent(ev2,true);
        Event ev3 = new Event(Color.RED,time, "Some extra data that I want to store.");
        calendar.addEvent(ev3,true);
        calendar.setListener(new CompactCalendarView.CompactCalendarViewListener() {
            @Override
            public void onDayClick(Date dateClicked) {
                List<Event> events = calendar.getEvents(dateClicked);
                Log.d("s", "Day was clicked: " + dateClicked + " with events " + events);
            }

            @Override
            public void onMonthScroll(Date firstDayOfNewMonth) {
                Log.d("s", "Month was scrolled to: " + firstDayOfNewMonth);
            }
        });
    }
}

**Comment by Faterjames** [comment]
Is anyone here to answer my questions,thanks a lot! I truly can not work that out !orz

**Comment by SundeepK** [comment]
@Faterjames Sorry I have been off on holiday for the past week. I'll have a look at this tomorrow. But from the looks of it this might be culprit `calendar.setLocale(TimeZone.getTimeZone("GMT"),Locale.CHINA);` Your locale should match timezone. Try commenting out that line to see if it fixes it.

**Comment by Faterjames** [comment]
I have already got rid of this question ,  it is a quite stupid mistake: the circle on current day cover that little dot !
now is there any method to make the dot draw after the current day circle be drawn?

**Comment by SundeepK** [comment]
Try this method `shouldDrawIndicatorsBelowSelectedDays()` this will draw the dot below the selected day and also show the big circle around day. This makes the big circle a little smaller though, so you can increase the height of calendar a little bit to accommodate. But that's up to you.

**Comment by SundeepK** [comment]
Closing this issue, please re-open if you need more help.
