### ISSUE TITLE
How to set colors programatically

### ISSUE THREAD

**Issue by BartlomiejRasztabiga** [SundeepK/CompactCalendarView#164]
Hi, I would like to know, what values should I pass to method e.g setCurrentDayBackgroundColor(). I see it should be int, but I can't find what exactly. Thanks in advance

**Comment by SundeepK** [comment]
https://developer.android.com/reference/android/graphics/Color.html

You can use for example `Color.parseColor("#fff"); // white`. It can take a hexidecimal color. `Color` provides many ways to get color values.

**Comment by BartlomiejRasztabiga** [comment]
Oh, thanks. I haven't thought about this :D
