### ISSUE TITLE
First day is always selected

### ISSUE THREAD

**Issue by florianhenonin** [SundeepK/CompactCalendarView#165]
When you scroll from month to an other, the first day is always "selected".

Exemple : 
I select 17th feb. 17th feb is selected. it's ok. 
Now I scroll to march : first day appear as selected (same for other months).
Only 17th feb have to be selected.

**Comment by SundeepK** [comment]
Hi, there should be an option in the latest version:

```
        app:compactCalendarShouldSelectFirstDayOfMonthOnScroll="true"
```

Set to false to disable this.

**Comment by florianhenonin** [comment]
Oh yes, thank you !
