### ISSUE TITLE
Different Day Text Color

### ISSUE THREAD

**Issue by sunit09** [SundeepK/CompactCalendarView#166]
Can I set different text colors for current day, selected day & other days?

**Comment by reeltimeapps** [comment]
+1 for this feature enhancement.

**Comment by ender1975** [comment]
I would also welcome this feature.

**Comment by nelo686** [comment]
I would like to have it too

**Comment by SundeepK** [comment]
I've released a new version which makes the colors for current and selected day configurable. Check the readme for the latest version.

**Comment by sunit09** [comment]
Thank You.. Working with charm
