### ISSUE TITLE
The same date of every year is being selected.

### ISSUE THREAD

**Issue by scm573** [SundeepK/CompactCalendarView#170]
Hi, I found that the same date of every year is being selected, at its default implementation, as well as calling .setCurrentDate() with a specified date.

In my case I want the calendar only selects the one day I set. Is there any way to switch off the drawing on the same dates of other years?

**Comment by SundeepK** [comment]
You can fork the code and change a few lines:
https://github.com/SundeepK/CompactCalendarView/blob/master/library/src/main/java/com/github/sundeepk/compactcalendarview/CompactCalendarController.java#L868

The `isSameMonthAsCurrentCalendar` checks for the month only. 
https://github.com/SundeepK/CompactCalendarView/blob/master/library/src/main/java/com/github/sundeepk/compactcalendarview/CompactCalendarController.java#L830

```
boolean isSameMonthAsCurrentCalendar = monthToDrawCalender.get(Calendar.MONTH) == currentCalender.get(Calendar.MONTH);
```

Is how the boolean value is initialised. Change to:

```
boolean isSameMonthAsCurrentCalendar = monthToDrawCalender.get(Calendar.MONTH) == currentCalender.get(Calendar.MONTH) &&  monthToDrawCalender.get(Calendar.YEAR) == currentCalender.get(Calendar.YEAR);
```

To detect the year as well. I think that should do it. Then changing years won't effect the way the day is selected.

**Comment by scm573** [comment]
Hi, @SundeepK 
Thanks for the reply.

I tried as you wrote and yes it works completely as expected.
And I also tried to add a flag for that to make it configurable. If you think it's useful could you please just take a look at the pull request.

#171 

Best

**Comment by lucasrafagnin** [comment]
I need the same solution

**Comment by SundeepK** [comment]
@lucasrafagnin Will have a chance this weekend to hopefully make some progress with the pull request.

**Comment by SundeepK** [comment]
Please allow some time for it to be available. Now use the `app:compactCalendarShouldSelectFirstDayOfMonthOnScroll="false"` in the xml properties and the only day that is selected is the current selected day.
```
dependencies {
    compile 'com.github.sundeepk:compact-calendar-view:2.0.1'
}
```
