### ISSUE TITLE
Right to Left support

### ISSUE THREAD

**Issue by NuclearGandhi** [SundeepK/CompactCalendarView#177]
I tried using the library for my Hebrew app (right to left language), and I noticed that the calendar didn't flip its layout (The columns' order should be flipped).
This can be easily fixed if in the CompactCalendarController.java class, if there was variable to store whether the local language is left to right (Hebrew and Arabic), and if it is right to left, then:

in drawMonth():
`float xPosition = widthPerDay * (6 - dayColumn) + paddingWidth + paddingLeft + accumulatedScrollOffset.x + offset - paddingRight; // Replaced dayColumn with (6 - dayColumn)`

in onSingleTapUp():
`int dayColumn = 6 - Math.round((paddingLeft + e.getX() - paddingWidth - paddingRight) / widthPerDay); //Added 6 -`

***
Edit:
I just noticed there is already an issue open for this, and I am terribly sorry for this. I hope that at least my suggestions helped you.

**Comment by SundeepK** [comment]
Thanks for having a look, as you know there is an open issue, but my time has been very limited in the last month. I have made some head way with the code but it's not finished. I'll try having a look this week and see if i can make some head way.

Marking as duplicate as #123 already exists.
