### ISSUE TITLE
How to show event according to month & year 

### ISSUE THREAD

**Issue by monikarora** [SundeepK/CompactCalendarView#179]
i want to show event in calendar according to month & year
{"status":"1","result":[
{"id":"2","color":"#FF0000","constraint":"2017-03-31"}
,{"id":"2","color":"#FF0000","constraint":"2017-04-21"},{"id":"2","color":"#FF0000","constraint":"2018-11-10"}
]}
Please help me .Thanks

**Comment by SundeepK** [comment]
You want to convert your list of results and into `Event` objects, something like below (not tested).

SimpleDateFormat sdfmt2= new SimpleDateFormat("yyyy-MM-dd");
Event ev1 new Event(Color.parseColor("#FF0000"), sdfmt2.parse("2017-03-31"));
compactCalendar.addEvent(ev1);

**Comment by monikarora** [comment]
thanks @SundeepK  i already done  my issue

**Comment by monikarora** [comment]
now i want selected month get Saturday & Sunday dates. because in my app i want to set color color at Saturday & Sunday dates

**Comment by monikarora** [comment]
private void addEvents(CompactCalendarView compactCalendarView, ArrayList<String> full_array, int j) {
     /*   SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
      String  formattedDate = df.format(currentCalender.getTime());
        currentCalender.setTime(new Date());
        currentCalender.set(Calendar.DAY_OF_MONTH, 1);

        Date firstDayOfMonth = currentCalender.getTime();
        Log.e("first",firstDayOfMonth+"");
        Log.e("currentCalender",currentCalender.getTime()+"");

*/

        String date = Arrays.toString(full_array.toArray()).replace("[", "").replace("]", ""); // new year
       /* String date2 = "28/01/2017"; // chinese new year
        String date3 = "29/01/2017"; // chinese new year
        String date4 = "01/05/2017"; // labour day
        String date5 = "10/05/2017"; // wesak
        String date6 = "31/8/2017"; // national day
        String date7 = "1/9/2017"; // Hari Raya Haji
        String date8 = "16/9/2017"; //Malaysia Day
        String date9 = "25/12/2017";*/ //Christmas
        Log.e("date", date);

        //String[] dateHoliday = {date};

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        // Calendar c= new Calendar[dateHoliday.length];
        Calendar[] c = new Calendar[full_array.size()];
        // Calendar c1 = new Calendar(dateHoliday.length);


        for (int i = 0; i < full_array.size(); i++) {
            Log.e("holidddd", full_array.size() + "");
            Log.e("holidddddddd", full_array + "");
            c[i] = Calendar.getInstance();
            try {
                c[i].setTime(sdf.parse(full_array.get(i)));

            } catch (ParseException e) {
                e.printStackTrace();
            }

            Event Full_event = new Event(Color.parseColor("#FF0000"), c[i].getTimeInMillis(), "hello");
            Event available_event = new Event(Color.parseColor("#48D1CC"), c[i].getTimeInMillis(), "hello");
            Event peak_event = new Event(Color.parseColor("#FFD700"), c[i].getTimeInMillis(), "hello");

            
            if (j == 2)
                compactCalendarView.addEvent(peak_event, true);
            if (j == 3)
                compactCalendarView.addEvent(Full_event, true);
            if (j == 4)
                compactCalendarView.addEvent(available_event, true);
        }

**Comment by monikarora** [comment]
now i want selected month get Saturday & Sunday dates. because in my app i want to set color
at Saturday & Sunday dates
