### ISSUE TITLE
how to go to current month.

### ISSUE THREAD

**Issue by Frankenstein666** [SundeepK/CompactCalendarView#185]
I'd like add a toolbar menu item to go to current month in the calendarview, how can i do that?

**Comment by SundeepK** [comment]
Using the `onCreate()` and `onResume()` you can assign a Date object to a class field called `currentDate` in your activity/fragement class. On click of the menu item, call `compactCalendar.setCurrentDate(currentDate)`;

That is a the way to do it now. There is now method to goto the current month right now.

**Comment by Frankenstein666** [comment]
okay, do i need to format  the current date object argument to any specific format using simpleDateFormat pattern to pass date object to compactCalendar.setCurrentDate() method??

**Comment by SundeepK** [comment]
Any `Date` object can be used.

**Comment by Frankenstein666** [comment]
so i don't need formatting?

**Comment by SundeepK** [comment]
No aslong as you set the correct date time in the object, it will work.
