### ISSUE TITLE
Can I display the previous month before 1 day?

### ISSUE THREAD

**Issue by dengyuhan** [SundeepK/CompactCalendarView#194]
Can this be configured?
the last month also shows, but the color is shallow.

![1](https://cloud.githubusercontent.com/assets/17588779/25660122/6bd9c648-303d-11e7-967d-5b67930ba561.png)

**Comment by SundeepK** [comment]
Hi, you can use the method `displayOtherMonthDays(boolean value)`. It takes a boolean. If you pass true, it will draw previous month greyed out. Check below:

https://github.com/SundeepK/CompactCalendarView/blob/master/library/src/main/java/com/github/sundeepk/compactcalendarview/CompactCalendarView.java#L325

You can also set the color using xml attribute `compactCalendarOtherMonthDaysTextColor`:

https://github.com/SundeepK/CompactCalendarView/blob/master/library/src/main/res/values/attrs.xml#L29
