### ISSUE TITLE
refresh issue

### ISSUE THREAD

**Issue by KPriyanka** [SundeepK/CompactCalendarView#196]
Hello ,
I have implemented CompactCalendarView. I have one spinner above that shows list of customers , as per customers , number of dotd changes. I am scrolling CompactCalendarView went to next month, then changed the customer name. I want the CompactCalendarView to come to current month on every new selection. Please do help. CompactCalendarView.invalidate() is not helping me.

**Comment by SundeepK** [comment]
You can use the `setCurrentDate(Date date)` to set the current date on the calendar. That will cause it to show that month.
