### ISSUE TITLE
How to Populate All year festival list as Event ,and on click particular event show it on below calendar like other calendar apps. Please give me any solution

### ISSUE THREAD

**Issue by akshusaraf28** [SundeepK/CompactCalendarView#197]
And it is accept other than millisecond format?

**Comment by SundeepK** [comment]
Check the sample app, it shows what you are asking for in simplified way. You can use `Date` object as well.

I'm not sure what you mean by "All year festival list" but you can use a for loop to loop through any days/months/years to add events. Again check the sample app for examples.

**Comment by SundeepK** [comment]
Did you manage to solve the problem? I'm closing for now, please re open if more questions.
