### ISSUE TITLE
Method to change dayColumnNames

### ISSUE THREAD

**Issue by GabiR** [SundeepK/CompactCalendarView#2]
You should implement a method to change dayColumnNames from CompactCalendarController. This way you can let people set day names from their language.

**Comment by SundeepK** [comment]
Do you intend to add single characters for the days, or use abbreviations. For example, is {"M", "T", "W" ..} valid as well as {"Mon", "Tue", "Wed"}. I think I could allow a max range between 1-3 and not have to change the code. Any more than that, then I'd have to either trim characters off or resize column names if there is enough space to show the full name of the day. Looks like some investigation might be needed.

**Comment by GabiR** [comment]
It's okay. 3 characters are enough. But if it's not possible 1 character is
also good enough.

2015-06-08 13:57 GMT+03:00 Sundeep Kahlon <notifications@github.com>:

**Comment by SundeepK** [comment]
Should now be available in version 1.4.

**Comment by SundeepK** [comment]
I think another better way to approach this is get the day names from Calendar object, so it should pick up what ever is set in the JVM I think. I'll raise another issue for this and see if I can make things a little easier. I'll probably leave this method in as a second measure.
