### ISSUE TITLE
Event dot indicator not showing after restarting app

### ISSUE THREAD

**Issue by AhmedEzio47** [SundeepK/CompactCalendarView#202]
I'm saving the events in a file when I add them in a certain app run the dot appear normally but the problem comes when I restart the app this won't appear again. So is there any way I can redraw the Event Dot Indicator after restarting the app.

**Comment by SundeepK** [comment]
You will have to load all the events since everything is held in memory. But that is a good point. Maybe there should be an option to write to a file and read automatically.

**Comment by AhmedEzio47** [comment]
I still don't understand how will please show me how here's my code `public class MainActivity extends 
AppCompatActivity {

    CompactCalendarView compactCalendar;


    SimpleDateFormat fullDate = new SimpleDateFormat("MMM dd yyyy HH:mm");
    SimpleDateFormat evTime = new SimpleDateFormat("HH:mm");
    SimpleDateFormat month = new SimpleDateFormat("MMMM - YYYY");
    SimpleDateFormat day = new SimpleDateFormat("MMM dd yyyy");

    public MainActivity() throws IOException {
    }


    void saveData(String fileName, String key, Set<String> values){
        SharedPreferences sharedPref = getSharedPreferences(fileName, Context.MODE_PRIVATE);
        SharedPreferences.Editor editor = sharedPref.edit();
        editor.putStringSet(key, values);
        editor.apply();
    }

    Set<String> loadData(String fileName, String key){
        SharedPreferences sharedPref = getSharedPreferences(fileName, Context.MODE_PRIVATE);
        Set<String> vals = sharedPref.getStringSet(key, new HashSet<String>());
        return vals;
    }

    void eventMaker(String d, String ev)  {

        Date date = null;

        try {
            date = fullDate.parse(d);
        } catch (ParseException e) {
            e.printStackTrace();
        }

        String time = evTime.format(date);

        try {
            date = day.parse(d);
        } catch (ParseException e) {
            e.printStackTrace();
        }

        long epoch = date.getTime();
        Event event = new Event(Color.RED,epoch,ev);
        compactCalendar.addEvent(event);

        if(loadData("eventList", d)==null){
            Set<String> eventList = new HashSet<>();
            eventList.add(ev);
            saveData("eventList",date.toString(),eventList);

            Set<String> eventTimes = new HashSet<>();
            eventTimes.add(time);
            saveData("eventTimes",date.toString(),eventTimes);
        }
        else{

            Set<String> eventList = loadData("eventList", date.toString());
            eventList.add(ev);
            saveData("eventList",date.toString(),eventList);

            Set<String> eventTimes = loadData("eventTimes", date.toString());
            eventTimes.add(time);
            saveData("eventTimes",date.toString(),eventTimes);
        }

        }




    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        final ActionBar actionBar = getSupportActionBar();
        actionBar.setDisplayHomeAsUpEnabled(false);

        compactCalendar = (CompactCalendarView) findViewById(R.id.compactcalendar_view);
        actionBar.setTitle(month.format(compactCalendar.getFirstDayOfCurrentMonth()));
        compactCalendar.setUseThreeLetterAbbreviation(true);


        //Uncomment for code testing
        eventMaker("May 08 2017 10:30","Quiz");
        eventMaker("May 08 2017 08:45","Lecture");
        eventMaker("May 18 2017 10:15", "Revision" );
        eventMaker("Jun 18 2017 12:30", "Final Exam" );



        compactCalendar.setListener(new CompactCalendarView.CompactCalendarViewListener() {
            TextView events = (TextView) findViewById(R.id.events);
            @Override
            public void onDayClick(Date dateClicked) {

                Context context = getApplicationContext();

     if(!loadData("eventList",dateClicked.toString()).isEmpty()) {
         events.setText("");

         Set<String> eventList =loadData("eventList",dateClicked.toString());
         Set<String> eventTimes = loadData("eventTimes",dateClicked.toString());

         for(int i=0; i<eventList.size(); i++){
             String output = (i+1)+"-"+eventList.toArray()[i]+" at "+eventTimes.toArray()[i]+"\n\n";
             events.append(output);
         }

     }
                else{
                    events.setText("NO EVENT PLANNED FOR THIS DAY");
                    Toast.makeText(context,"No Event",Toast.LENGTH_SHORT).show();

        }

        }
        @Override
            public void onMonthScroll(Date firstDayOfNewMonth) {
                events.setText("");
                actionBar.setTitle(month.format(firstDayOfNewMonth));
            }
        });
    }
}`

**Comment by SundeepK** [comment]
From what I can tell the key (string date) you are saving in the preferences is different from what you get on click listener when you select a day. So it will never load the data correctly? 

Why don't you store data per a month and year basis? E.g. new key is "07-2017". Then on month scroll load the events for the whole month. You can do this for `current month + 1` and `current month - 1` and current month so you have a 3 month window and there will always be events showing when user scrolls.

I would also suggest using a database if you have lots of events. There are many options in android such as sql or realm.

**Comment by AhmedEzio47** [comment]
Thank you for your help, I really appreciate it, it kinda rare these day, you're a good man thanks.
