### ISSUE TITLE
ViewPager Horizontal scroll not handled when visibility set to GONE

### ISSUE THREAD

**Issue by Anthony-Reboul** [SundeepK/CompactCalendarView#203]
When a visible CompactCalendarView is set to Visibility.GONE, its still catch and handle the touch event on it's old display area. Even is the method shouldScrollMonth(false) is called. 

So when this view is placed into a ViewPager and visibility is set to GONE, the ViewPager wont be able to handle the horizontal scroll in the view old area.

The technical reason is that the overridden method canScrollHorizontally always return true instead for returning this.shouldScroll.

**Comment by SundeepK** [comment]
Hi, I was wondering if it's possible to upload an example project show casing the problem so that I can have a look? That would be really useful. This change was made for this issue here raised a while back:

https://github.com/SundeepK/CompactCalendarView/pull/117

Here's the commit: https://github.com/SundeepK/CompactCalendarView/commit/d3a5ef9191cd9baddbd9b3deda6236bbd7309dd7

I wonder if we need to check if the view is visible then use the default `super` implementation otherwise return true?

**Comment by SundeepK** [comment]
I should add the sample app has a `ViewPager` with the calendar inside it. I set it to `GONE` and was still able to scroll. Perhaps it's the code is different to the way you have set things up.

**Comment by Anthony-Reboul** [comment]
Hi, to reproduce the issue, the calendar has to be GONE, then it's visibility set to visible and switched back to GONE. In my case, the calendar is inside a CardView and the CardView visibility is changed.

I have checked the issue #117 before creating the pull request and it won't be affected by this changes (the method canScrollHorizontally will still return true as long as horizontalScrollEnabled is set to true, which is it's default value).

Checking if the visibility is set to GONE is a very good idea, so the user don't have to call shouldScrollMonth(false) manually. But I think you should also check the value of horizontalScrollEnabled, because if it's set to false, the method canScrollHorizontally shouldn't in any case return true.

I won't have time to create an example project in the next days, but here is a video of the issue and a second video after the fix.

Issue #203 : https://www.youtube.com/watch?v=0qvbcdN9ZnA
Issue #203 Fixed : https://www.youtube.com/watch?v=dqolB5Dz48w

**Comment by SundeepK** [comment]
Changes merged.
