### ISSUE TITLE
Days divider

### ISSUE THREAD

**Issue by MatheusDinni** [SundeepK/CompactCalendarView#204]
Hello, first of all your library is awesome, thank you!

Is there a way to set dividers between days? Make a line on drawables and set it programatically or xml, like
app:setItenDivider="drawable/item_divider or app:setLinesBetweenDays="true".

**Comment by SundeepK** [comment]
Hi sorry for late response. Currently not supported out of the box, but might be possible to do. Do you mean draw a single line between each day of the week so you have 6 lines separating the days?

**Comment by MatheusDinni** [comment]
Yes, something like that. Lines between days and weeks, the part of customizating them can be a little deeper than a default line and the user could only set it's height and visible or not. Okay, this is not something that hinders the operation, just layout thing.

Cheers!

**Comment by SundeepK** [comment]
If you want to draw a grid, there is an issue here which might be of interest:
https://github.com/SundeepK/CompactCalendarView/issues/148

**Comment by SundeepK** [comment]
Drawing a line separation would also not be too difficult to achieve. I can have a look at the code to see a good way to do this if you would like.

**Comment by MatheusDinni** [comment]
Thanks, but no need, you can close the topic. The issue indicated already gave me an orientation.
