### ISSUE TITLE
hebrew/arabic days

### ISSUE THREAD

**Issue by morkuk** [SundeepK/CompactCalendarView#208]
while im trying to use the calendar with hebrew/arabic days, I don't get the acutal days.
for example:
![image](https://user-images.githubusercontent.com/28810901/27050411-0beba63c-4fbb-11e7-9f79-54dfef9399eb.png)

![image](https://user-images.githubusercontent.com/28810901/27050424-1f1ea0b0-4fbb-11e7-853a-77b27062b2d9.png)
strange thing though. since my windows10 is in hebrew, i manage to see in preview the correct way:

![image](https://user-images.githubusercontent.com/28810901/27050465-49ed02aa-4fbb-11e7-9aba-ae7ce0ceceb6.png)

this is how it supposed to look.
how to fix it?

**Comment by SundeepK** [comment]
Hi can you show me how you are setting up the calendar so that I can give it a try. If you can so me your xml layout and java code I can give it a try.

**Comment by morkuk** [comment]
Hey sundeepk, I managed to fix it. 
if anyone else want the code: 
`     compactCalendarView.setFirstDayOfWeek(Calendar.SUNDAY);

        String[]names = new String[7];
        names[0]="ראשון"; // sunday
        names[1]="שני"; // monday
        names[2]="שלישי"; // tuesday
        names[3]="רביעי"; // wednesday
        names[4]="חמישי"; // thursday 
        names[5]="ששי"; // friday
        names[6]="שבת"; // saturday 
        compactCalendarView.setDayColumnNames(names);`

**Comment by SundeepK** [comment]
There is an RTL support beta 
```
dependencies {
    compile 'com.github.sundeepk:compact-calendar-view:2.0.3-beta'
}
```

**Comment by SundeepK** [comment]
Can you also show me your java code for setting this up? I would like to have better integration with rtl

**Comment by morkuk** [comment]
@SundeepK 
`public class CompactCalendarTab extends Fragment {

    private static final String TAG = "MainActivity";
    private Calendar currentCalender = Calendar.getInstance(Locale.getDefault());
    private SimpleDateFormat dateFormatForDisplaying = new SimpleDateFormat("dd-M-yyyy hh:mm:ss a", Locale.getDefault());
    private SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy", Locale.ENGLISH);
    private SimpleDateFormat dateFormatForMonth = new SimpleDateFormat("MMM - yyyy", Locale.getDefault());
    private boolean shouldShow = false;
    private CompactCalendarView compactCalendarView;
    //private ActionBar toolbar;
    TextView showdate;
    Intent chooseDateAct;
  //  static List<Event> list_events;
    String json;
    SharedPreferences preferences;
    Date date_clicked;
    Calendar cal= Calendar.getInstance();
    static long time_clicked;
    List<danielisakov.whenholiday.Event> emptyList;
    int current_month, chosen_month, current_year, chosen_year;
    SharedPreferences.Editor editor;
    final List<String> mutableBookings = new ArrayList<>();
    ArrayAdapter adapter;

    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View v = inflater.inflate(R.layout.calendar_tab,container,false);
        //list_events = new ArrayList<>();
        preferences = this.getActivity().getPreferences(0);


        final ListView bookingsListView = (ListView) v.findViewById(R.id.bookings_listview);
        final ImageButton showPreviousMonthBut = (ImageButton) v.findViewById(R.id.prev_button);
        final ImageButton showNextMonthBut = (ImageButton) v.findViewById(R.id.next_button);
        //final Button slideCalendarBut = (Button) v.findViewById(R.id.slide_calendar);
        //final Button showCalendarWithAnimationBut = (Button) v.findViewById(R.id.show_with_animation_calendar);
        //final Button setLocaleBut = (Button) v.findViewById(R.id.set_locale);
        //final Button removeAllEventsBut = (Button) v.findViewById(R.id.remove_all_events);

        adapter = new ArrayAdapter<>(getContext(), android.R.layout.simple_list_item_1, mutableBookings);
        bookingsListView.setAdapter(adapter);
        compactCalendarView = (CompactCalendarView) v.findViewById(R.id.compactcalendar_view);

        // below allows you to configure color for the current day in the month
        // compactCalendarView.setCurrentDayBackgroundColor(getResources().getColor(R.color.black));
        // below allows you to configure colors for the current day the user has selected
        // compactCalendarView.setCurrentSelectedDayBackgroundColor(getResources().getColor(R.color.dark_red));
        compactCalendarView.setUseThreeLetterAbbreviation(false);
        compactCalendarView.setFirstDayOfWeek(Calendar.SUNDAY);

        String[]names = new String[7];
        names[0]="ראשון";
        names[1]="שני";
        names[2]="שלישי";
        names[3]="רביעי";
        names[4]="חמישי";
        names[5]="ששי";
        names[6]="שבת";
        compactCalendarView.setDayColumnNames(names);

        //addEvents(5, 2017);
        //addEvents(6,2017);

        current_month = currentCalender.get(Calendar.MONTH);
        current_year = currentCalender.get(Calendar.YEAR);
        List<danielisakov.whenholiday.Event> bookingsFromMap = getEvents(currentCalender.getTimeInMillis(),1);
        if (bookingsFromMap != null) {
            Log.d(TAG, bookingsFromMap.toString());
            mutableBookings.clear();
            for (danielisakov.whenholiday.Event booking : bookingsFromMap) {
                String date =  formatter.format(booking.getTimeInMillis());
                mutableBookings.add(booking.getEventName()+ "("+booking.getEventType()+ ")" + " בתאריך " +date);

            }
            adapter.notifyDataSetChanged();
        }
        //loadEvents();
        //loadEventsForYear(2017);
         //offset by 1
        compactCalendarView.invalidate();

       // logEventsByMonth(compactCalendarView);

        chooseDateAct = new Intent(getActivity(), ChooseDateActivity.class);

        // below line will display Sunday as the first day of the week
        // compactCalendarView.setShouldShowMondayAsFirstDay(false);

        // disable scrolling calendar
        // compactCalendarView.shouldScrollMonth(false);

        // show days from other months as greyed out days
        // compactCalendarView.displayOtherMonthDays(true);

        // show Sunday as first day of month
        // compactCalendarView.setShouldShowMondayAsFirstDay(false);

        //set initial title
        //toolbar = ((ActionBarActivity) getActivity()).getSupportActionBar();
        showdate = (TextView) v.findViewById(R.id.showdate);
        Typeface myCustomFont = Typeface.createFromAsset(getActivity().getAssets(), "font/VarelaRound-Regular_1.ttf"); // find my font
        showdate.setTypeface(myCustomFont);
        showdate.setText(dateFormatForMonth.format(compactCalendarView.getFirstDayOfCurrentMonth()));
        // toolbar.setTitle(dateFormatForMonth.format(compactCalendarView.getFirstDayOfCurrentMonth()));

        //set title on calendar scroll
        compactCalendarView.setListener(new CompactCalendarView.CompactCalendarViewListener() {
            @Override
            public void onDayClick( Date dateClicked) {
                //toolbar.setTitle(dateFormatForMonth.format(dateClicked));
                  date_clicked=dateClicked;
                startActivity(chooseDateAct);
                time_clicked =date_clicked.getTime();
                showdate.setText(dateFormatForMonth.format(dateClicked));

                Log.d(TAG, "inside onclick " + dateFormatForDisplaying.format(dateClicked));
                //Toast.makeText(getContext(), "" + dateClicked, Toast.LENGTH_SHORT).show();


            }


            @Override
            public void onMonthScroll(Date firstDayOfNewMonth) {
                //toolbar.setTitle(dateFormatForMonth.format(firstDayOfNewMonth));
                showdate.setText(dateFormatForMonth.format(firstDayOfNewMonth));

            }
        });

        showPreviousMonthBut.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                compactCalendarView.showPreviousMonth();
                if(current_month==0) {
                    current_month=11;
                    current_year= current_year-1;
                }

                else
                    current_month--;
                currentCalender.set(Calendar.MONTH, current_month);
                List<danielisakov.whenholiday.Event> bookingsFromMap = getEvents(currentCalender.getTimeInMillis(),1);
                if (bookingsFromMap != null) {
                    Log.d(TAG, bookingsFromMap.toString());
                    mutableBookings.clear();
                    for (danielisakov.whenholiday.Event booking : bookingsFromMap) {
                        String date =  formatter.format(booking.getTimeInMillis());
                        mutableBookings.add(booking.getEventName()+ "("+booking.getEventType()+ ")" + " בתאריך " +date);
                    }
                    adapter.notifyDataSetChanged();
                }
            }
        });

        showNextMonthBut.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                compactCalendarView.showNextMonth();
                if(current_month==11) {
                    current_month=0;
                    current_year = current_year+1;
                }

                else
                    current_month++;
                currentCalender.set(Calendar.MONTH, current_month);
                List<danielisakov.whenholiday.Event> bookingsFromMap = getEvents(currentCalender.getTimeInMillis(),1);
                if (bookingsFromMap != null) {
                    Log.d(TAG, bookingsFromMap.toString());
                    mutableBookings.clear();
                    for (danielisakov.whenholiday.Event booking : bookingsFromMap) {
                        String date =  formatter.format(booking.getTimeInMillis());
                        mutableBookings.add(booking.getEventName()+ " ("+booking.getEventType()+ ")" + " בתאריך " +date);
                    }
                    adapter.notifyDataSetChanged();
                }
            }
        });

        /*final View.OnClickListener showCalendarOnClickLis = getCalendarShowLis();
        slideCalendarBut.setOnClickListener(showCalendarOnClickLis);

        final View.OnClickListener exposeCalendarListener = getCalendarExposeLis();
        showCalendarWithAnimationBut.setOnClickListener(exposeCalendarListener);*/

        compactCalendarView.setAnimationListener(new CompactCalendarView.CompactCalendarAnimationListener() {
            @Override
            public void onOpened() {
            }

            @Override
            public void onClosed() {
            }
        });

       /* setLocaleBut.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Locale locale = Locale.FRANCE;
                dateFormatForDisplaying = new SimpleDateFormat("dd-M-yyyy hh:mm:ss a", locale);
                TimeZone timeZone = TimeZone.getTimeZone("Europe/Paris");
                dateFormatForDisplaying.setTimeZone(timeZone);
                dateFormatForMonth.setTimeZone(timeZone);
                compactCalendarView.setLocale(timeZone, locale);
                compactCalendarView.setUseThreeLetterAbbreviation(false);
                loadEvents();
                loadEventsForYear(2017);
                logEventsByMonth(compactCalendarView);

            }
        });

        removeAllEventsBut.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                compactCalendarView.removeAllEvents();
            }
        });*/


        // uncomment below to show indicators above small indicator events
        // compactCalendarView.shouldDrawIndicatorsBelowSelectedDays(true);

        // uncomment below to open onCreate
        //openCalendarOnCreate(v);

        return v;
    }

    @NonNull
    private View.OnClickListener getCalendarShowLis() {
        return new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (!compactCalendarView.isAnimating()) {
                    if (shouldShow) {
                        compactCalendarView.showCalendar();
                    } else {
                        compactCalendarView.hideCalendar();
                    }
                    shouldShow = !shouldShow;
                }
            }
        };
    }

    @NonNull
    private View.OnClickListener getCalendarExposeLis() {
        return new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (!compactCalendarView.isAnimating()) {
                    if (shouldShow) {
                        compactCalendarView.showCalendarWithAnimation();
                    } else {
                        compactCalendarView.hideCalendarWithAnimation();
                    }
                    shouldShow = !shouldShow;
                }
            }
        };
    }

    private void openCalendarOnCreate(View v) {
        final RelativeLayout layout = (RelativeLayout) v.findViewById(R.id.calendar_tab);
        ViewTreeObserver vto = layout.getViewTreeObserver();
        vto.addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
            @Override
            public void onGlobalLayout() {
                if (Build.VERSION.SDK_INT < 16) {
                    layout.getViewTreeObserver().removeGlobalOnLayoutListener(this);
                } else {
                    layout.getViewTreeObserver().removeOnGlobalLayoutListener(this);
                }
                compactCalendarView.showCalendarWithAnimation();
            }
        });
    }

    @Override
    public void onResume() {
        super.onResume();
        List<danielisakov.whenholiday.Event> bookingsFromMap = getEvents(currentCalender.getTimeInMillis(),1);
        if (bookingsFromMap != null) {
            Log.d(TAG, bookingsFromMap.toString());
            mutableBookings.clear();
            for (danielisakov.whenholiday.Event booking : bookingsFromMap) {
                String date =  formatter.format(booking.getTimeInMillis());
                mutableBookings.add(booking.getEventName()+ "("+booking.getEventType()+ ")" + " בתאריך " +date);
            }
            adapter.notifyDataSetChanged();
        }
        //toolbar.setTitle(dateFormatForMonth.format(compactCalendarView.getFirstDayOfCurrentMonth()));
        showdate.setText(dateFormatForMonth.format(compactCalendarView.getFirstDayOfCurrentMonth()));
        // Set to current day on resume to set calendar to latest day
        // toolbar.setTitle(dateFormatForMonth.format(new Date()));
    }

  /*  private void loadEvents() {
        addEvents(-1, -1);
        addEvents(Calendar.DECEMBER, -1);
        addEvents(Calendar.AUGUST, -1);
    }

    private void loadEventsForYear(int year) {
        addEvents(Calendar.DECEMBER, year);
        addEvents(Calendar.JUNE, year);
    }
    */

 /*   private void logEventsByMonth(CompactCalendarView compactCalendarView) {
        currentCalender.setTime(new Date());
        currentCalender.set(Calendar.DAY_OF_MONTH, 1);
        currentCalender.set(Calendar.MONTH, Calendar.AUGUST);
        List<String> dates = new ArrayList<>();
        for (danielisakov.whenholiday.Event e : compactCalendarView.getEventsForMonth(new Date())) {
            dates.add(formatter.format(e.getTimeInMillis()));
        }
        Log.d(TAG, "Events for Aug with simple date formatter: " + dates);
        Log.d(TAG, "Events for Aug month using default local and timezone: " + compactCalendarView.getEventsForMonth(currentCalender.getTime()));
    } */

  /* private void addEvents(int month, int year) {
        currentCalender.setTime(new Date());
        currentCalender.set(Calendar.DAY_OF_MONTH, 1);
        Date firstDayOfMonth = currentCalender.getTime();
        if(list_events!=null)
            if(!list_events.isEmpty())
        for (int i = 0; i < list_events.size(); i++) {
            currentCalender.setTime(firstDayOfMonth);
            if (month > -1) {
                currentCalender.set(Calendar.MONTH, month);
            }
            if (year > -1) {
                currentCalender.set(Calendar.ERA, GregorianCalendar.AD);
                currentCalender.set(Calendar.YEAR, year);
            }
            if(date_clicked!=null) {
                cal.setTime(date_clicked);
                time_clicked = cal.getTimeInMillis();
                currentCalender.add(Calendar.DATE, cal.get(Calendar.DAY_OF_MONTH) - 1);
                setToMidnight(currentCalender);
                long timeInMillis = currentCalender.getTimeInMillis();


                List<danielisakov.whenholiday.Event> events = getEvents(timeInMillis, cal.get(Calendar.DAY_OF_MONTH) - 1);

                compactCalendarView.addEvents(events);
            }
        }
    } */

    private List<danielisakov.whenholiday.Event> getEvents(long timeInMillis, int day) {

    /*    if (day < 2) {
            return Arrays.asList(new AnEvent(Color.rgb(77,182,172), timeInMillis, "שם אירוע בתאריך "  + new Date(timeInMillis)));
        } else if ( day > 2 && day <= 4) {
            return Arrays.asList(
                    new AnEvent(Color.rgb(77,182,172), timeInMillis, "שם אירוע בתאריך " + new Date(timeInMillis)),
                    new AnEvent(Color.rgb(38, 166, 154), timeInMillis, "שם אירוע 2 בתאריך " + new Date(timeInMillis)));
        } else {
            return Arrays.asList(
                    new AnEvent(Color.rgb(77,182,172), timeInMillis, "שם אירוע בתאריך " + new Date(timeInMillis) ),
                    new AnEvent(Color.rgb(38, 166, 154), timeInMillis, "שם אירוע 2 בתאריך " + new Date(timeInMillis)),
                    new AnEvent(Color.rgb(0, 150, 136), timeInMillis, "שם אירוע 3 בתאריך "  + new Date(timeInMillis)));

        }*/

        Type type = new TypeToken<List<danielisakov.whenholiday.Event>>() {
        }.getType();
        if (courses_list == null)
            courses_list = getActivity().getPreferences(0);
        json = courses_list.getString("MyEvents", "");
        List<danielisakov.whenholiday.Event> inpList = new Gson().fromJson(json, type);

        if (inpList != null) {

            int i = 0;
            while (!inpList.isEmpty() && i < inpList.size()) {
                cal.setTimeInMillis(inpList.get(i).getTimeInMillis());
                chosen_month = cal.get(Calendar.MONTH);
                chosen_year = cal.get(Calendar.YEAR);
                if (chosen_month != current_month || chosen_year != current_year ) {
                    inpList.remove(i);
                    i--;
                }
                    i++;

                }
            }
            if (json.equals("")) {
                emptyList = new ArrayList<>();
                return emptyList;
            }

            return inpList;
        }


    private void setToMidnight(Calendar calendar) {
        calendar.set(Calendar.HOUR_OF_DAY, 0);
        calendar.set(Calendar.MINUTE, 0);
        calendar.set(Calendar.SECOND, 0);
        calendar.set(Calendar.MILLISECOND, 0);
    }

}`

**Comment by SundeepK** [comment]
Closing this issue since I don't think there is a problem. The day names which is shown is usually based on whatever the jvm will provide it. Usually you can use `setDayColumnNames` to set specific names or `setUseThreeLetterAbbreviation` to show more characters. After my testing with these methods, it seemed to work, but I don't know Hebrew. Please re-open if you think there is something that needs to be done.

**Comment by killer010** [comment]
how can i change the position of the event that is been added
and
also there appearance
![capture](https://user-images.githubusercontent.com/34153075/33471445-7e1ef7cc-d693-11e7-9046-2d52d727c4bd.PNG)

 can u pls help me with this
