### ISSUE TITLE
Selection of the month by clicking on the date toolbar

### ISSUE THREAD

**Issue by pseudnyme** [SundeepK/CompactCalendarView#209]
Hello,

Is it possible to quickly change month / year in a different way than by clicking the left and right buttons?

Thx

**Comment by SundeepK** [comment]
There are a few ways, `setCurrentDate()`, `showNextMonth()` and `showPreviousMonth()` methods are all available. `setCurrentDate` takes any date object.

**Comment by pseudnyme** [comment]
No really, i was thinking about a datePicker to switch for exemple from march 2017 to august 2018 quickly.

Is it something like that included ?

**Comment by jmamegroot** [comment]
@pseudnyme you can create your own date picker and set the date with the method setCurrentDate. Is that wat you mean?

**Comment by pseudnyme** [comment]
That's exactly what I was looking for. I'm a beginner, sorry for this :)

thx for your help guys
