### ISSUE TITLE
How to  disable dates ?

### ISSUE THREAD

**Issue by monikarora** [SundeepK/CompactCalendarView#210]
Hey @SundeepK   i want to disable dates less than to current date . is it possible ? 
Please help me .

**Comment by SundeepK** [comment]
This is an existing open issue #84. I can't give an update since I have not started it. But since amny people are asking, i will have a think about it.

**Comment by monikarora** [comment]
Okay :(

**Comment by VikhyatC** [comment]
Is it done?

**Comment by shoaibfarhan1** [comment]
Dear Sandeep, Still we are waiting for your update regarding disable the future and past dates in compactcalendarview..

**Comment by VikhyatC** [comment]
Hey @shoaibfarhan1 i was successfully able to put the validation from my side. Just display a foreground dialog box such that it is uncancellable.Check the validation every time a date clicked this worked for my solution.
