### ISSUE TITLE
set custom adapter to the listview in the fragment

### ISSUE THREAD

**Issue by morkuk** [SundeepK/CompactCalendarView#212]
hey @SundeepK , I know it's not about the calendar, but I thought you can help...
I have used your listview in the calendar page, and now I am trying to add a Delete button, so my user can remove his events. 
so obviously there's the calendar.xml page:
https://pastebin.com/8ciu225W
![image](https://user-images.githubusercontent.com/28810901/27182019-875f14a6-51e2-11e7-9f50-043d50654a0c.png)

and then there's the fragment activity, for the calendar & the listview. 
https://pastebin.com/wS4s0GEG

I created custom adapter class called MyCustomAdapter.java:
https://pastebin.com/qiypgs6G

and I have list_item.xml:
https://pastebin.com/Ey8gK8Lf

what do you think? how can I set this custom adapter in the fragment? I have an adapter already, for the event the user type in (that's in other java class, when he click on a day there's a window pops up on the screen, I can post this too, if you want)

what I am trying to do:
![image](https://user-images.githubusercontent.com/28810901/27181941-498eb726-51e2-11e7-9a67-ae8dcb02c209.png)
(this custom adapter called in an class extends Activity & I add the items myself like this: ArrayList<String> list = new ArrayList<String>();
        list.add("item1");
        list.add("item2");
        list.add("item3");
        list.add("list4");
        list.add("item5");
)

**Comment by SundeepK** [comment]
Hi, did you manage to solve the problem?

I would think you can setup the adapter based on the current events of the month. Simple query the calendar for all events for that month and update the adaptor with that list. Then when a user clicks the delete button, have a listener setup to remove the events from the calendar and re-query the calendar and refresh the adapter.

**Comment by morkuk** [comment]
I used something else, thanks anyway!
