### ISSUE TITLE
Group days selection

### ISSUE THREAD

**Issue by GGLabCenter** [SundeepK/CompactCalendarView#215]
Hi, I sent to you an email with details some week ago. Btw, it would be possible to have the selection of a group of days? eg. instead of setting an event with the single dot to a day, it would be nice to select a range of days and (for example) selecting them with a soft background color. Thanks for this beautiful library.

**Comment by SundeepK** [comment]
Hi there is already an issue raised for this #97. Have a look, in short, I would like todo this but I just don't have time currently. In the ticket, someone has already done this by modifying the calendar as shown in that issue. So it's definitely possible.

**Comment by GGLabCenter** [comment]
Sorry i didn't see the one you linked to me (1year old). I am really sorry
for that, but I understand. I will try to do my best to make that function
available for my needs. I will also send to you my results (it could be
useful for others asking for it) if I will succeed in managing that. Thanks
for your work, have a nice day

Il 12 lug 2017 11:54 AM, "SundeepK" <notifications@github.com> ha scritto:
