### ISSUE TITLE
Can not Swipe ViewPager 

### ISSUE THREAD

**Issue by yeonsik** [SundeepK/CompactCalendarView#218]
I wish that ViewPager(+ Fragments) is Swipe.
However, with this scheduler in Fragment I can not Swipe ViewPager. How do I do Swipe?

**Comment by SundeepK** [comment]
Hi, how do you have the code setup? The sample app uses a view pager and fragment and it works as expected. Try cloning the project and run the sample app and see if it works.

What android version are you using and what phone/emulator? What does your xml layout look like?

**Comment by yeonsik** [comment]
I do not want to swipe the calendar in ViewPager. I want to swipe the fragment itself in the ViewPager.

When the ViewPager has the Home Fragment and the Event Fragment, I want to move to the Events Fragment if I swipe in the Home Fragment.

I would be pleased if you could tell me how to do so.

**Comment by SundeepK** [comment]
In that case, have you tried `compactCalendarView.shouldScrollMonth(false);`

This will disable month scrolling and allow you to move between fragments, you just won't be able to scroll between months, which is what I think you want?

**Comment by yeonsik** [comment]
I know the option. but I did want to swipe the fragments when try **scroll on CompactCalendarView**.
If I use the option, calendar and fragment All are not swiped when I try **scroll on CompactCalendarView**.

**Comment by SundeepK** [comment]
Ok, I'm not 100% sure what you need but if you can upload a very simple example project in github. I can then clone and debug the app on a device so that I can understand your requirement by seeing the problem. Is that ok? Maybe in your app there is some different configuration.

When I tried that method in the sample app, I was able to scroll between the fragments whilsts my finger was on the calendar it self, just the calendar was no longer handling the scroll event and passing back to the view pager.

**Comment by yeonsik** [comment]
Sorry. I can't speaking English well.
You can test your sample app. I'm upload this image for explanation.

![compactcalendarview](https://user-images.githubusercontent.com/485222/28623768-ebac09ac-7251-11e7-8392-52d507c2272a.jpg)

**Comment by SundeepK** [comment]
Are you debugging sample app from master? If not what version of the library are you using? The below is the latest version:

```
dependencies {
    compile 'com.github.sundeepk:compact-calendar-view:2.0.2.2'
}
```

**Comment by yeonsik** [comment]
I used 2.0.2.1. I updated to 2.0.2.2 now and I see resolved the issue. Thank you!
