### ISSUE TITLE
CompactCalendarView in Fragment

### ISSUE THREAD

**Issue by hbomb1977** [SundeepK/CompactCalendarView#22]
Hi SundeepK,

I'm trying to use your lib to show a calendar. Everything works on Activity, but i've got a problem on Navigation Drawer Activity.

I must clic on "Previous", "Next" button or somewhere on calendar to show it. On the fist time, only buttons are visibles (see below):
![capture](https://cloud.githubusercontent.com/assets/6532731/9789449/8ba73650-57d0-11e5-8cde-e1494c49dc38.png)

you can download my source code here:
http://hebergement.u-psud.fr/mobile/android/

i must use a navigation drawer because your calendar is a new feature of existing app. in fact, i must use "android.app.Fragment", not  the "support fragment". Our app is only available for API 16+

a last thing, in the menu, if i put "calendar fragment" on first fragment (the first showed) it works...

i think it must be a stupid mistake but i can't find it :(
thanks a lot for your help

hbomb

**Comment by SundeepK** [comment]
I haven't looked at the example yet, I will when I get time sometime later.

Quick reply. When you load the calendar oncreate view in your fragment. Try calling invalidate() on the calendar instance. This will cause it to redraw.

**Comment by hbomb1977** [comment]
thanks for your answer. i call the invalidate method into "onCreateView".

I found a solution, but i'm not sure that's the best practice. I use the "onResume" method to force reloading (so i need to declare compactCalendarView and adapter in class instead of into OnCreate method)

```java
    @Override
    public void onResume() {
        super.onResume();

        Handler handler = new Handler();
        Runnable updater = new Runnable() {
            public void run() {
                if(compactCalendarView != null) {
                    compactCalendarView.invalidate();
                    adapter.notifyDataSetChanged();
                }
            }
        };

        handler.post(updater);
    }
```
thanks for your help

hbomb

**Comment by SundeepK** [comment]
You shouldn't need to create a runnable, to do this, at least I don't think you need to. I'll have a look at your example on the weekend and let you know. Maybe the calendar is missing something? I'll have a play around with things.

Thanks.

**Comment by SundeepK** [comment]
Should be available in next release, which will be available over the next day or so.

**Comment by SundeepK** [comment]
Available in:

```gradle

dependencies {
    compile 'com.github.sundeepk:compact-calendar-view:1.7.3'
}

```

**Comment by hbomb1977** [comment]
thank you very much for your work, everything is ok now :)
