### ISSUE TITLE
Need to change days background circle style to square style background

### ISSUE THREAD

**Issue by gowtham29challenger** [SundeepK/CompactCalendarView#236]
Hi,
Thanks for such a nice library!
I need to change days background circle style to square style background, i.e when user selects the day, it should highlight in square style not in circle,and also vertical and horizontal spacing lines with color, for this what i need to do?

PFA attachment of screenshot
![android custom calendar](https://user-images.githubusercontent.com/32014492/30512155-201da9d4-9b06-11e7-9577-cc4023af540b.jpg)

**Comment by SundeepK** [comment]
Hi, this is similar to #148. Basically, you need to take a fork of the code and modify the code where it draws a letters to draw a rect instead.

**Comment by SundeepK** [comment]
Closing this issue as #148 basically describes how to do this.
