### ISSUE TITLE
FirstDayOfMonth not selectable

### ISSUE THREAD

**Issue by XxGoliathusxX** [SundeepK/CompactCalendarView#24]
Hey,
your calendar works fine but i cant select/click on the first day of month.
Here is an excerpt:

compactCalendarView.setListener(new CompactCalendarView.CompactCalendarViewListener() {
            @Override
            public void onDayClick(Date dateClicked) {
                System.out.println(dateClicked.toString());
            }
}

All the other days are selectable! 
Output example: "System out: Wed Sep 02 00:00:00 MESZ 2015"

**Comment by SundeepK** [comment]
Will release new version later today.

**Comment by SundeepK** [comment]
Available in:

```
dependencies {
    compile 'com.github.sundeepk:compact-calendar-view:1.7.5'
}
```
