### ISSUE TITLE
FirstDayOfMonth doesnt show event-feedback-circle

### ISSUE THREAD

**Issue by XxGoliathusxX** [SundeepK/CompactCalendarView#25]
Is it possible to make the look of the first day of month like a normal day? Because #1 usability is restricted. it doesnt show a circle below the "1". This feedback is very important for my app. Every day that has at least one event in it, has to show it!

**Comment by XxGoliathusxX** [comment]
it also doesnt show the big cycle if you click on it

**Comment by SundeepK** [comment]
Yes I'm currently working on making the Calendar work like the on in Google calendar app see #23 and also see #13.

I've already created a branch for this and I'm almost there. Should be there in the next few days just a few minor things. You can track the progress on the tickets.

Thanks

**Comment by SundeepK** [comment]
Closing since duplicate and work is now merged into master. Will release new version tomorrow.

**Comment by SundeepK** [comment]
Released in latest version, please allow some time for it to be available.

```
dependencies {
    compile 'com.github.sundeepk:compact-calendar-view:1.7.6'
}

```
