### ISSUE TITLE
Gradle Error

### ISSUE THREAD

**Issue by kjanjuha** [SundeepK/CompactCalendarView#278]
Hi there, I'm getting an issue with importing this package on Android Studio. Any ideas? It says its a 401 unauthorized error?

![image](https://user-images.githubusercontent.com/32637345/37432168-5e2409d4-27cf-11e8-899a-8c00a09dac85.png)

Cheers

**Comment by samsonpaul87** [comment]
Hi I am also facing the same issue. Could someone help me to fix this issue?

**Comment by VictorPurMar** [comment]
Same
