### ISSUE TITLE
1.7.6 Update Feedback

### ISSUE THREAD

**Issue by XxGoliathusxX** [SundeepK/CompactCalendarView#28]
First day of month works but now the currentday gives no feedback if its selected (Doesnt change color) and doesnt show a eventindicator cycle

**Comment by SundeepK** [comment]
It's how Google calendar works. Current day is highlighted in a special colour. If you select it, it doesn't change colour. Events are also not shown and as far as I can tell and there's no way of changing the colour for the current day.

Is this functionality important to you? I can add a method to make it configurable.

**Comment by XxGoliathusxX** [comment]
That would be nice. Its the only thing i miss, because in the actual condition the calendar loses on information demand. lets say the current day is the 17th and it has an event. when i click on a other day lets say the 5th --> the 17th doesnt show the small indicator cycle --> Only when i click on it i can see that there are events on it

**Comment by SundeepK** [comment]
Closing as #73 has been raise so just closing as a duplicate.
