### ISSUE TITLE
Left to right swap Increase the month

### ISSUE THREAD

**Issue by dheerajIPHS** [SundeepK/CompactCalendarView#281]
Hello Sir, Good afternoon,

Sir My app is in hebrew language and I want to Reverse the swap listener means, When user swap from left to right then Month increase.

So how can I achieve this functionality.

Thank you.

**Comment by SundeepK** [comment]
Hi just to add there is a  RTL support here:
    compile 'com.github.sundeepk:compact-calendar-view:2.0.3-beta'
It's in beta, but I really should merge this to master. Let me know if it works well for you.

**Comment by sharon2469** [comment]
Hey, SundeepK can you please give some more information about RTL?
because i am write: compile 'com.github.sundeepk:compact-calendar-view:2.0.3-beta' and run this on my app and still every thing is from left to right

**Comment by sundeepkalt** [comment]
@sharon2469 There should be a method available `setIsRtl` set that to true.

**Comment by sharon2469** [comment]
@sundeepkalt  You make my day 😃
