### ISSUE TITLE
How to show events in today's date  [help wanted] 

### ISSUE THREAD

**Issue by ithebk** [SundeepK/CompactCalendarView#285]
Events dots under date for today not showing. Please help me

**Comment by 4R7Jirayu** [comment]
You try this code after compactCalendar.addEvent(Event);

Date date = new Date();
List<Event> EventToday = compactCalendarView.getEvents(date);
        if (EventToday.size() > 0) {
           // do something           
        }

**Comment by ITheBK** [comment]
@4R7Jirayu My problem is I have added events in different dates and also in today's date. The indicator(dots) which is showing just below date is displaying fine with the dates other than today. But in today's date the event indicator not coming just below the date. Please help me 
![picsart_05-09-02 20 31](https://user-images.githubusercontent.com/9915308/39805392-5ee1dc52-5394-11e8-9d20-d3691626f59c.jpg)

**Comment by sundeepkalt** [comment]
@ITheBK Try the `shouldDrawIndicatorsBelowSelectedDays` option. It's a boolean flag which will draw the indicator below selected days. However, it will still display the indicator _below_ any highlighted day which will look odd if you have white as the selected background color I think. 

As far as I can tell google calendars also hides any indicators on highlighted days.

**Comment by ITheBK** [comment]
@SundeepK Thanks for your response, `shouldDrawIndicatorsBelowSelectedDays` is not helping me. For me on selected highlighted its okay to hide indicator, but in the above image, the date 9th is not selected its just highlighted to tell its today's date, there I need to show indicator.
(Much clear : How to show indicator on highlighted date where its not selected?). 

@SundeepK  Please help me

**Comment by ConradLetelier** [comment]
@ITheBK - Did you get this to work somehow? I have the same problem

**Comment by ITheBK** [comment]
@ConradLetelier No Issue is still there!

**Comment by sundeepkalt** [comment]
@ITheBK If you want to try and fix it, you can take a fork of the code and remove the `isSameDayAsCurrentDay` variable from the if condition here:

https://github.com/SundeepK/CompactCalendarView/blob/master/library/src/main/java/com/github/sundeepk/compactcalendarview/CompactCalendarController.java#L769

**Comment by denghanhao** [comment]
compactCalendarView.shouldDrawIndicatorsBelowSelectedDays(true);

**Comment by sjla** [comment]
@ithebk did you find the solution to show event on current date.I am facing the same issue.

**Comment by ithebk** [comment]
@sjla Haven't resolved.

**Comment by ithebk** [comment]
@sjla 
`compactCalendarView.shouldDrawIndicatorsBelowSelectedDays(true);`
Above method worked.
Showing indicator was not a requirement for me so not checked for this issue, Just tried above method, now calendar shows event indicator below the selected date as well as today's date.

**Comment by sjla** [comment]
@ithebk Shoulddrawindicator is working but i want to know there is a way to make current day same as all day.I know i can do this using currentdaybackhroundcolor but in case of event on current date this will not work,so what should i do.?
