### ISSUE TITLE
Error connecting

### ISSUE THREAD

**Issue by sanyok7734** [SundeepK/CompactCalendarView#29]
When connecting this error: 
Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/home/sanyok/IDE/android-sdk-linux/build-tools/22.0.0/aapt'' finished with non-zero exit value 1

I would be very grateful if you say that is not so

**Comment by sanyok7734** [comment]
With version 1.7.5 all right, but my need version 1.7.6

**Comment by SundeepK** [comment]
If you just updated, the xml attributes have changed:


```
        app:compactCalendarFirstDayOfMonthBackgroundColor="#E57373"
```

to:

```
        app:compactCalendarCurrentSelectedDayBackgroundColor="#E57373"
```

**Comment by sanyok7734** [comment]
Thenk you.
