### ISSUE TITLE
Event "dots" are not showing

### ISSUE THREAD

**Issue by Zeckarai** [SundeepK/CompactCalendarView#290]
I have great use for your calendar and it has worked really well untill now! For some reason the dots indicating events do not show up? Perhaps I'm missing something fundemental.

I add events using the .addEvents method and I have checked for them being there using system outputs. Has this issue occurred before? Is there some method I need to use to make the dots appear?

**Comment by sundeepkalt** [comment]
If you add events for the current day, I think they will not show because the current day is always highlighted. 

How are you adding the events? Can you give examples?

**Comment by Zeckarai** [comment]
`CompactCalendarView ccw = alertView.findViewById(R.id.compactcalendar_view);

ArrayList<Event> list = new ArrayList<>();
for(EventInfo event : eventList) {
      list.add(new Event(getResources().getColor(R.color.logoblue), getMilliTime(event), event));
}

ccw.addEvents(list);`

As such, I have a different "event" object that I put as the "data" object in the event. The events that I put in there should not be saved on the current day.

The "getMilliTime(event)" works as such: 
`Long getMilliTime(EventInfo eventInfo){
        Long millitime = null;
        try{
            Date date = eventTimeStamps.parse(eventInfo.startTime);
            millitime = date.getTime();
        }
        catch (ParseException e){
            e.printStackTrace();
        }

        return millitime;
    }`

**Comment by Zeckarai** [comment]
Well I found the problem, and it's a bit shameful... Used the wrong letter when creating my SimpleDateFormat. Used "DD" instead of "dd"...
