### ISSUE TITLE
button and scroll conflict

### ISSUE THREAD

**Issue by bij-ace** [SundeepK/CompactCalendarView#30]
if im on Jan 2015 and i scroll (not button press) to Apr 2015, then i press previous button it takes me to Feb 2015. why is this happening?

**Comment by SundeepK** [comment]
Thanks for pointing that out it looks like a bug. I'll investigate this one. Actually I might be able to write a test for it as well.

**Comment by SundeepK** [comment]
Since I added that functionality, the java calendars might be getting in an inconsistent state. Again, java calendar class is mutable and awkward :(.

**Comment by XxGoliathusxX** [comment]
I tested it in my calendar iand i got march the 1st fine

**Comment by SundeepK** [comment]
It's in master, try and see if it solves the problem. I think it should be fixed. Looks like you have to scroll a few months backwards/forwards and then use the buttons to scroll months. It''ll update the calendar to an incorrect month.

**Comment by SundeepK** [comment]
Available in:

```
dependencies {
    compile 'com.github.sundeepk:compact-calendar-view:1.7.7'
}
```

**Comment by bij-ace** [comment]
yes it is solved. thank u :)
