### ISSUE TITLE
indicator issue

### ISSUE THREAD

**Issue by bij-ace** [SundeepK/CompactCalendarView#31]
if i click on date with event and then click other date, the indicator is not re-apperaing.

**Comment by SundeepK** [comment]
Are you talking about event indicator in the sample? There is a line in the code which removes the event on day click:

https://github.com/SundeepK/CompactCalendarView/blob/master/sample/src/main/java/sundeepk/github/com/sample/MainActivity.java#L80

**Comment by bij-ace** [comment]
i want it to be removed when that date is selected but i want it to reappear when i click other date

**Comment by SundeepK** [comment]
Then delete that line in the sample code. It will no longer remove the event from the calendar.

**Comment by bij-ace** [comment]
yes but is there any way to hide the indicator only when it is selected, then on clicking other day it will be visible again?

**Comment by SundeepK** [comment]
Sorry I don't quite understand. Lets start from the beginning. What is it exactly you need to do?

There are 3 types of indicators. No. 1 indicator for events (small circle below day in the sample). No. 2 indicator for the current day (dark red in sample) and No. 3 indicator for currently selected day (light red in sample).

Which one of these do you want to show when an event is selected?

The calendar will draw the light red circle when ever you select a day except when you select the current day (No. 2 dark circle) even if there is an event indicator.

**Comment by bij-ace** [comment]
im talking about the small one for events (ie No. 1). initailly when the sample code is executed they are shown. but when i click on the date which has event, the small indicator disappears on that particular date and when i click on other date it never appears again on that date. so is there any way to make the small indicator appear on that date again when i choose other date?

**Comment by bij-ace** [comment]
i solved it by adding addEvents(compactCalendarView); like this:

@Override
            public void onDayClick(Date dateClicked) {
                date.setText(dateFormatForMonth.format(dateClicked));
                List<Booking> bookingsFromMap = bookings.get(dateClicked);
                mutableBookings.clear();
                if(bookingsFromMap != null){
                    Log.d("MainActivity", bookingsFromMap.toString());
                    for(Booking booking : bookingsFromMap){
                        mutableBookings.add(booking.title);
                    }
                }
                c
                compactCalendarView.removeEvent(new CalendarDayEvent(dateClicked.getTime(), Color.argb(255, 169, 68, 65)), true);
                adapter.notifyDataSetChanged();
            }

sorry for all the trouble and thanks :)

**Comment by SundeepK** [comment]
Are you running the sample code? This seems to be working fine for me as long as you delete/comment out line 80 in the MainActvitiy class.

**Comment by SundeepK** [comment]
Yep thats the line which removes events. I'm going to remove that line from the MainAcitivty to get rid of any confusion :).

Thanks.
