### ISSUE TITLE
how many events does the calendar support

### ISSUE THREAD

**Issue by ramonamorea** [SundeepK/CompactCalendarView#319]
First, thank you so much for this component! It's great and easy to customize and works well, I love it!

My issue is rather a question.

How many events the calendar supports?

I'm developing a school app, I want to add an event for every day of school year. So...about 200+ events...Will it work? Will this affect the app performance? Thank you!

**Comment by gregdev** [comment]
@ramonamorea I have very extensively modified my CompactCalendarView but this should still be relevant - I currently have one event per day from June 2018 - present (about 265 events all up), and my calendar shows a different image on each day that has an event, and performance is fine. I download events from a custom REST API, and just load up the currently-viewed month and the next and previous month - there's no need to load all events unless the user goes back or forward far enough in the calendar to view them.

**Comment by ramonamorea** [comment]
Thank you so much! I did what you said.

When I open the calendar, I show the events for the current month.
Then, when the users scrolls back or forward the calendar, I load the events for that month which is visible. This work very well (and I have a total of 400 events!)

Thanks again, I"ll close this issue/question for now.

**Comment by a619sachin** [comment]
> @ramonamorea I have very extensively modified my CompactCalendarView but this should still be relevant - I currently have one event per day from June 2018 - present (about 265 events all up), and my calendar shows a different image on each day that has an event, and performance is fine. I download events from a custom REST API, and just load up the currently-viewed month and the next and previous month - there's no need to load all events unless the user goes back or forward far enough in the calendar to view them.

Can you please guide me with the REST API event fetch.
