### ISSUE TITLE
Start week with Sunday

### ISSUE THREAD

**Issue by bij-ace** [SundeepK/CompactCalendarView#32]
Is it possible to start the week with Sunday instead of Monday?

**Comment by SundeepK** [comment]
This is a feature request, will have to be added as a method or xml attribute. Probably a boolean flag.

**Comment by ankushtiwari03** [comment]
Can you pls tell by example how it can be achieved ?

**Comment by SundeepK** [comment]
Hi, sorry for the delayed reply. I have been very busy these past few weeks. However, I plan to get started on this by the weekend. Currently, however, this isn't supported.

**Comment by chaosxeras** [comment]
Hello SundeepK, I just started learning Android Studios about 4 weeks ago. I found your Calendar View very useful. I was toying around with the built in calendar view, but I read on stackflow that I can't add events unless I make a custom one. Anyways, I'm here to say thanks and to tell you that I am using your work.

**Comment by SundeepK** [comment]
@chaosxeras :thumbsup:

**Comment by SundeepK** [comment]
Almost done with this issue, have a look at branch and commit 9a1aae0 if you want to test things out.

**Comment by SundeepK** [comment]
Available in:
```
 dependencies {
    compile 'com.github.sundeepk:compact-calendar-view:1.7.9'
}
```

**Comment by jaytj95** [comment]
Setting this variable does nothing for me. Is there an extra step?

**Comment by SundeepK** [comment]
@jaytj95 what version are of android and the library are you using? It should be simple as calling something like `compactCalendarView.setShouldShowMondayAsFirstDay(false);` It works in the sample app provided in the main repo running nexus 6p.
