### ISSUE TITLE
Indicator too small on high resolution device

### ISSUE THREAD

**Issue by bij-ace** [SundeepK/CompactCalendarView#33]
indicator is very small on high resolution devices. can we something about this?

**Comment by bij-ace** [comment]
compactCalendarView.drawSmallIndicatorForEvents(false);

**Comment by SundeepK** [comment]
I think this is a legitimate problem, so re-opening. Some people will want to keep drawing the small indicator. I can add an attribute in xml to set the size in dp and also add a setter.

**Comment by bij-ace** [comment]
ok :+1:

**Comment by SundeepK** [comment]
Available in 

```
dependencies {
    compile 'com.github.sundeepk:compact-calendar-view:1.7.8'
}
```
