### ISSUE TITLE
Quick way to go to the current date/month after Swiping Left and Right 

### ISSUE THREAD

**Issue by kprathap23** [SundeepK/CompactCalendarView#38]
I swipe Right for 5 times now i am on April 2016. I want to go to my current date on button click event.

**Comment by kprathap23** [comment]
Got it.

 compactCalendarView.setCurrentDate(Calendar.getInstance(Locale.getDefault()).getTime());

**Comment by SundeepK** [comment]
Hi, there is a ```setCurrentDate(Date date)``` method that you can use. For example, create a button and in the listener, and call ``` compactCalender.setDate(new Date())```

**Comment by kprathap23** [comment]
Thanks. Is there any Month Change Listener after swipe . I want to get data from service after swipe for every month
