### ISSUE TITLE
Displaying month and year

### ISSUE THREAD

**Issue by vijaysaimutyala** [SundeepK/CompactCalendarView#47]
The calendar was awesome. but sorry for raising the issue. How do I get to display the month and year?

**Comment by SundeepK** [comment]
Where do you want to display the month and year? You can get the current month and year by calling ``` getFirstDayOfCurrentMonth()  ``` which returns a ```Date``` object, then you can update any UI element with this data.

Check the sample code that comes along, which might be useful.

**Comment by vijaysaimutyala** [comment]
Thank you, have checked the sample, it was wonderful. Thank you.
