### ISSUE TITLE
Attribute textSize has already been defined

### ISSUE THREAD

**Issue by GabiR** [SundeepK/CompactCalendarView#5]
When importing your library, the textSize attribute is conflicting with an attribute from another library because they have the same name.

This is a known Android issue (namespaces aren't taken in consideration). 

Can you please fix it, putting a prefix before your attributes from attrs.xml (for example transform <attr name="textSize" format="dimension"/> in <attr name="ccTextSize" format="dimension"/> or something else)  ?

**Comment by SundeepK** [comment]
I'm going to be explicit with this then and prevent any other ambiguity. I'll prefix attribute names with compactCalendar. It will be a breaking change for people but I'll add a note in the readme :trollface:.

**Comment by GabiR** [comment]
thanks. can you also put the change on maven?

**Comment by SundeepK** [comment]
Yep, once this one is fixed. Probably sometime later today.

**Comment by SundeepK** [comment]
Should now be available.
