### ISSUE TITLE
2 events in same day

### ISSUE THREAD

**Issue by miibpa** [SundeepK/CompactCalendarView#60]
Is it possible to show more than one dot under the day when there are more than 1 events in a single day?

**Comment by SundeepK** [comment]
Hi there is already an issue raised #52.  I don't really have a plan on what issues I do first. But I moslty pick up things that more people want.

Closing as its a duplicate.

**Comment by septemberboy7** [comment]
Hello, I want to display only one dot. How can I do that?

**Comment by SundeepK** [comment]
Then add only one event to the calendar for that specific day.
