### ISSUE TITLE
allowBackup should not be set

### ISSUE THREAD

**Issue by joshafeinberg** [SundeepK/CompactCalendarView#62]
Inside the library manifest, allowBackup is set to true

`android:allowBackup="true"`

Problem is, if you have allowBackup set to false in the application manifest it causes a compilation error.

**Comment by samerzmd** [comment]
have tried this 
http://stackoverflow.com/a/13806946/2148631

**Comment by joshafeinberg** [comment]
The problem isn't that I'm getting a lint error. Its that in my application manifest, I set the backup to false. In the library manifest, it sets it to true. Therefore it can't compile because it doesn't know which setting to use.

Is there a reason the library needs allowBackup set to true?

**Comment by SundeepK** [comment]
Umm, must have been committed by accident. If you want to send a pull request, I can merge that in now. Or I'll fix it later on today.

**Comment by joshafeinberg** [comment]
#63 Added the pull request

**Comment by SundeepK** [comment]
Closing issue since PR was merged.
