### ISSUE TITLE
Can change the event background colors of event dates instead of small indicators

### ISSUE THREAD

**Issue by Vishulucky** [SundeepK/CompactCalendarView#69]
Hi ,
Can change the background color of event dates instead of small indicators 
Thanks

**Comment by SundeepK** [comment]
Hi, do you mean change color of the text that has a event in it? Currently this is not supported. However, if you mean something else, then please describe things a little more. Thanks.

**Comment by SundeepK** [comment]
I believe this should be aviable in version 1.9.1. Please have a look at issue #80.

**Comment by rameshmedical** [comment]
is this issues resolved
