### ISSUE TITLE
show Previous/Next Month's days

### ISSUE THREAD

**Issue by wiaamLB** [SundeepK/CompactCalendarView#70]
Hello,
Thank you for this awesome Calendar :+1: 
I want to show the date of previous and next month like in the picture 
Thanks :)
![capture](https://cloud.githubusercontent.com/assets/19538693/15481811/0fb5fe12-2135-11e6-8711-110d6e585e5b.PNG)

**Comment by antoxa2584x** [comment]
+1

**Comment by SundeepK** [comment]
Hi there is issue #46 for this. I'll have a look at this very soon. Thanks!

Will close as duplicate.

**Comment by SundeepK** [comment]
This has now been implemented, and will be released soon. Please track #46  for further updates.
