### ISSUE TITLE
How to highlight a day which is having some events?

### ISSUE THREAD

**Issue by shyamsam** [SundeepK/CompactCalendarView#75]
I have got some dates from server, I want those  dates to be highlighted in the calendar. How can I achieve it?

**Comment by SundeepK** [comment]
You need to add events:

```java
 Event ev1 new Event(Color.GREEN, 1433701251000L, "Some extra data that I want to store.");
 calendar.addEvent(ev1);
```
You can also add a list of events to the calendar `addEvents`. You will get an indicator showing below the date. Please see sample app and readme.

**Comment by SundeepK** [comment]
I'm going to assume that fixed your problem, so closing issue.
