### ISSUE TITLE
Is it possible to refresh view ?

### ISSUE THREAD

**Issue by shyamsam** [SundeepK/CompactCalendarView#76]
I have added some events to calendar. Upon selecting some dates, the previously highlighted events has to be refreshed. Is it possible to refresh the calendar view

**Comment by SundeepK** [comment]
Hi, can you give a bit more detail on the problem your facing, maybe show some code. If you run the sample app, you can see selecting dates has no effect on events.

When adding events, there are a few things to consider. The calendar provides 2 methods to add an event:

```java 
        // Add event 1 on Sun, 07 Jun 2015 18:20:51 GMT
        Event ev1 new Event(Color.GREEN, 1433701251000L, "Some extra data that I want to store.");
        compactCalendar.addEvent(ev1);
```

or 

```java 
        // Add event 1 on Sun, 07 Jun 2015 18:20:51 GMT
        Event ev1 new Event(Color.GREEN, 1433701251000L, "Some extra data that I want to store.");
        compactCalendar.addEvent(ev1, false); // or true for auto invalidate
        compactCalendar.invalidate();
```

The second parameter tell the calendar whether or not to invalidate the view i.e. to redraw. It's more of an optimisation. If your adding 100 events, you probably want to set that to false and then once you add all events, call `calendar.invalidate()`. Remember all views have `invalidate()` which tells it to redraw itself i.e. refresh. 

However, I would recommend using the `compactCalendar.addEvents()` method which takes in a list of events and invalidates the view. This method was added after adding single events.

```java
// Add event 1 on Sun, 07 Jun 2015 18:20:51 GMT
        Event ev1 new Event(Color.GREEN, 1433701251000L, "Some extra data that I want to store.");
        List<Event> events = new ArrayList();
        events.add(ev1);
        compactCalendar.addEvents(events);
```

**Comment by SundeepK** [comment]
Going to assume this answer fixed problem. Closing issue.
