### ISSUE TITLE
coloring date based on past event

### ISSUE THREAD

**Issue by yfsx** [SundeepK/CompactCalendarView#81]
hi, thankyou for creating this good library!

i wanna ask, is it possible to coloring date based on what even occurred on the past?
let says today is Friday. On Monday, Tuesday, and Thursday i entered school and my date on calendar marked with green color. But i got sick at Wednesday and my date on calendar marked with red color. The rest of dates marked with default color.

is this case possible to be implemented on this library? thanks!

**Comment by SundeepK** [comment]
Hi, sorry for the delayed response, I seemed to have missed this issue. Have a look at #80, is it similar to what you want?

**Comment by SundeepK** [comment]
I'm going to close since theres been no further activity here. I think #80 is what you wanted and its now already available.
