### ISSUE TITLE
Doesn't scroll properly inside ViewPager

### ISSUE THREAD

**Issue by nmoskalenko** [SundeepK/CompactCalendarView#82]
I'm trying to use CompactCalendarView on the fragment inside ViewPager.
CompactCalendarView control doesn't scroll properly - ViewPager scrolls instead of calendar.

**Comment by SundeepK** [comment]
Have a look at this issue #39, because it might be related. I believe someone implemented some fix for it, I have not yet tested things out with viewpager, but there might be some conflict between ontouch events being consumed by viewpager and not making it to the calendar.

**Comment by nmoskalenko** [comment]
Thank you for such a quick response!
You are absolutely right about conflict with viewpager on touch events.

I fixed the issue for myself just extending your control and overriding onTouchEvent
Also, I filed the pull request for you with this fix. Please consider it.

P.S.
Thank you for such a good control. I'll use it in my pet project.

**Comment by SundeepK** [comment]
Merged to master, will apply my changes for the sample project that includes the calendar inside a viewpager.

**Comment by SundeepK** [comment]
Just an update, I updated the main sample app to use a viewpager as an example to prove that this works. I can see my unit tests pass, so I will release a new version sometime today/tomorrow after I merge those changes to master.

**Comment by SundeepK** [comment]
Released under:
```
dependencies {
    compile 'com.github.sundeepk:compact-calendar-view:1.8.5'
}
```
