### ISSUE TITLE
i want to show the all events of month in list is it possible???

### ISSUE THREAD

**Issue by ashishCDN0135** [SundeepK/CompactCalendarView#85]
its working proper for me but will u plz tell me that is it possible to show all the events of month in the list rather then particular day events on day click..

**Comment by SundeepK** [comment]
Hi, currently there is no method for this, but it's simple code change. I'll see if I can get this done either today or tomorrow.

**Comment by ashishCDN0135** [comment]
ok thanks,any help will be really appreciated..

**Comment by ashishCDN0135** [comment]
hellow sundeep, i am waiting for ur reply did u mange any method for the particular task..

**Comment by SundeepK** [comment]
Hi sorry for the slow update, but there was actually more work than I expected. But I think I am now finished. I have added a new method: `compactCalendar.getEventsForMonth(Date date)`, when you pass it a date, it will look at that month and get the `Event` objects for it. You will get a sorted list starting from the first day of the month to the last.

**Comment by SundeepK** [comment]
Released under:

```
dependencies {
    compile 'com.github.sundeepk:compact-calendar-view:1.8.6'
}
```

Should be available in repository soon.

**Comment by SundeepK** [comment]
There was a bug I introduced which meant that all events where not being removed correctly, I have fixed the simple bug already. I'll release a new version again today. You can see the bug in #92 which I have fixed already. I would wait till the new version is released before using the new method.

**Comment by SundeepK** [comment]
fixed in:

```
dependencies {
    compile 'com.github.sundeepk:compact-calendar-view:1.8.7'
}
```
