### ISSUE TITLE
Selecting multiple days

### ISSUE THREAD

**Issue by hanoud90** [SundeepK/CompactCalendarView#86]
Hi there,

First of all, awesome library thanks a lot for that! 
Is there a way to be able to select multiple days? For example:
1. Click on day 1 - highlight day 1 only with circle 
2. Click on day 2 - highlight day 2 and day 1 with circle 
1. Click on day 1 again - unselect day 1, highlight day 2 only.

Many thanks for your help

**Comment by hanoud90** [comment]
Or actually, something that might be simpler, can I change the background of a specific day? 
That way I can listen to a day being selected and set a background colour for a day / unset background colour if the day had already been selected.

Thanks a lot for your help

**Comment by SundeepK** [comment]
Hi, this is currently not supported. One way to support it would be that highlighted days could be events but I'm guessing you still want the small indicators below the days as well. I can't make any promises on when this will get done, but I'm more than happy to tell you how to do it if you want to take a fork of the code and try for your self.

**Comment by hanoud90** [comment]
Thanks for the quick reply Sundeep!

I understand your point, if you could point me in the right direction so I could fork your code that would be brilliant :)

Many thanks,

**Comment by SundeepK** [comment]
Hi sorry for the delayed response, I just realised that this issue seems simialr to #80. Can you have a look? I intend to look at this sometime in the next few days so it would be useful as I think that issue describes a simialr scenario. If not can you describe how it differs?

**Comment by hanoud90** [comment]
Hi Sundeep, yep this is exactly what I want to do! If you do manage to get this functionality in that would be brilliant! :) thanks a lot!

**Comment by SundeepK** [comment]
Ok thanks, will close this ticket so we can comunicate on that ticket. I suggest to watch that ticket as well as there will be updates on that.
