### ISSUE TITLE
Is showing week wise view using this calender.

### ISSUE THREAD

**Issue by Sudheerbolla** [SundeepK/CompactCalendarView#87]
Is it possible to display week wise view along with month wise view.I want to display both month and week wise.Kindly help me.

**Comment by SundeepK** [comment]
Hi, there is already a issue #66 open. I was working on this issue until I got distracted with other pull requests and  small enhancements. But I plan on continuing this work. If this si what you want then I will mark this as a duplicate.

**Comment by Sudheerbolla** [comment]
Yup.sure.You can mark it as duplicate.But kindly update it a bit fast....got struck on it.:p
