### ISSUE TITLE
No Month Name

### ISSUE THREAD

**Issue by AriezF** [SundeepK/CompactCalendarView#88]
I'm using note 5 to display this calendar,. there is no month name.

**Comment by SundeepK** [comment]
Hi, you must add that yourself using a Textview or add that to your toolbar. Check the sample for more info.

**Comment by AriezF** [comment]
i cant seem to open the sample file, would you kind enough to explain it to me?

**Comment by SundeepK** [comment]
Here is an example: 
https://github.com/SundeepK/CompactCalendarView/blob/master/sample/src/main/java/sundeepk/github/com/sample/CompactCalendarTab.java#L87

Basically, you register a callback listener. When you scroll a month, you get notified along with the date. You can then update your text view or toolbar with the date. The link above works with toolbar.

Here's an example of the `onCreateView` for a fragment:

```java

    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View v = inflater.inflate(R.layout.main_tab,container,false);
        // get the calendar
        final CompactCalendarView compactCalendarView = (CompactCalendarView) v.findViewById(R.id.compactcalendar_view);
        //set initial title
        // get the Toolbar
        final ActionBar toolbar = ((ActionBarActivity) getActivity()).getSupportActionBar();
        toolbar.setTitle(dateFormatForMonth.format(compactCalendarView.getFirstDayOfCurrentMonth()));

        //set title on calendar scroll
        compactCalendarView.setListener(new CompactCalendarView.CompactCalendarViewListener() {
            @Override
            public void onDayClick(Date dateClicked) {
            }

            @Override
            public void onMonthScroll(Date firstDayOfNewMonth) {
                toolbar.setTitle(dateFormatForMonth.format(firstDayOfNewMonth));
            }
        });

        return v;
}

```

Remember, you don't have to use a toolbar, you can display however you want. As long as you update the view on month scroll, it wil update when ever someone scrolls.

**Comment by SundeepK** [comment]
I'm gonna close, but re-open if you require more help.

**Comment by Ryan5096** [comment]
I'm struggling to highlight date range ... it supports? how is the implementation...
Thanks in advance.
