### ISSUE TITLE
Remove First Day as SelectedDayBgColor

### ISSUE THREAD

**Issue by MhtSuthar** [SundeepK/CompactCalendarView#90]
I want to remove first day bg drawcirlce when scroll not next and prevous month!

**Comment by akhilesh9205** [comment]
looking for same.

**Comment by ShenYo** [comment]
looking for same too.  thx!

**Comment by robbyl** [comment]
I did it by setting color to transparent  app:compactCalendarCurrentSelectedDayBackgroundColor="@android:color/transparent"

**Comment by SundeepK** [comment]
Hi, does this mean you want to remove the highlight only when scrolling between months? But you want to keep is when the user selects a day or the current month?

**Comment by ShenYo** [comment]
Yeah! that's right.

**Comment by SundeepK** [comment]
@robbyl  What version of the calendar are you using? I believe I had that functionality previously, but I removed it so that I could keep things more inine with google calendars.

**Comment by SundeepK** [comment]
@ShenYo Thanks for the clarification.

**Comment by MhtSuthar** [comment]
I want to remove default selected or highlighted first day of month

**Comment by MhtSuthar** [comment]
@robbyl  if i try your code my selected day also gets deselected i want to keep that color existed when i select the day but not when i scroll and not selecting any day

**Comment by l540144279** [comment]
the same question ! want to remove the default selected or highlighted first day of month,and remember the day which users select and keep the selected status. thanks very much! have you resolved this question ? @MhtSuthar

**Comment by Bevor** [comment]
@SundeepK 
The default behaviour should actually be to not unselect a selected date, even when scrolling.
That means:
- I select Oct 26, then I scroll to the next or previous month, say November.
- November must not be selected.
- I scroll back to October, Oct 26 should still be selected.

**Comment by Lidgett** [comment]
I know its not a great fix however you can make it kind of work by setting the background color to transparent on swipe listener and then to your desired color when user clicks on the actual date.  
Set shouldDrawIndicatorsBelowSelectedDays(true) so events will appear if present.  Now I know they will be lower but as I said this is a quick fix until SundeepK can resolve this.  
And if viewing this SundeepK, would just adding the option for users to remove the drawable programmatically when they desire be the easiest option for you?

**Comment by derBinder** [comment]
Is there already an official fix for this?

**Comment by SundeepK** [comment]
@derBinder Will try and have a look at the issue this week.

**Comment by SundeepK** [comment]
Is there any point in have a boolean switch for this to support current functionality and this proposed one? I could just remove the bit of code which does this and it will make things nicer rather than having to support both ways. I.e. if month scroll, don't highlight first day of the month but keep the current selected day highlighted.

If you wanted to show first day of month after a scroll, I think the user can call `setCurrentDate` using the onscroll listener. That listener does indeed pass in the new month that has been scrolled, so you can select the first day of the month if you wanted using a few lines of code.

Any opinions?

**Comment by derBinder** [comment]
I think having a boolean switch to toggle the selection of the first day at month scroll is a good idea.

**Comment by Lidgett** [comment]
Personally I'd be fine with the removal of code.  It doesn't make sense adding code if unnecessary.  As you mentioned if we needed to continue with this action then we still have the option to setCurrentDate.
Although that being said, perhaps the majority like this feature and removal of it will cause more backlash than it's worth so applying a boolean value of some sort would please both parties without upsetting too many folks.
Not much help I know, just trying to consider others too.  
For me either way is better so you can't go wrong :-)

**Comment by SundeepK** [comment]
@Lidgett I agree, I think it would be good to maintain backwards compatibility in this case especially because if people upgrade, they will find that this feature is now suddenly missing.

Random update: I've taken then the boolean switch approach and working on some test code right now. Expect this to be done very soon.

**Comment by Lidgett** [comment]
Excellent!  Could you let us know when it's official, I'll need to search through some of my code to remove the hack.  Thanks Sundeep!!!

**Comment by SundeepK** [comment]
Added new xml property and method:

```xml
        app:compactCalendarShouldSelectFirstDayOfMonthOnScroll="true"
```

Set that to false to not select first day of month. Released anew version:

```gradle
dependencies {
    compile 'com.github.sundeepk:compact-calendar-view:1.9.8'
}
```

Please allow some time for it to be available.

**Comment by ShenYo** [comment]
@SundeepK 
It works great!  Thanks!
By the way~  it only works on your support library version >= 24

**Comment by akshusaraf28** [comment]
Thanks buddy it is a great calendar lib, This issue is fixed
