### ISSUE TITLE
how to set Thursday as first day of the week?

### ISSUE THREAD

**Issue by rastha67** [SundeepK/CompactCalendarView#93]

**Comment by SundeepK** [comment]
I think a method like `setFirstDayOfWeek(int firstDayOfWeek)` will work. Where you pass in an Int constant , which would be listed here: http://docs.oracle.com/javase/6/docs/api/java/util/Calendar.html#DAY_OF_WEEK

For example:
`calendat.setFirstDayOfWeek(Calendar.Monday);`

**Comment by TinasheMzondiwa** [comment]
Has this been implemented yet? 
I would like to set Sunday as first day of the week and not the default Monday?

**Comment by OliverMannhart** [comment]
I am also very interested in this feature. I also wonder if it is possible to donate/sponsor this project to get certain issues faster done?

**Comment by SundeepK** [comment]
Thanks for the interest, I should have time during the coming holiday to address some of the issues. If you can hold till then, I should have an update on this. I tend to do features which have most interest/upvotes.

**Comment by OliverMannhart** [comment]
Thanks for the fast reply.
Thats okay for me. I will vote for my favorite issues. :)

**Comment by carl1990** [comment]
yeah,I face this requirement also. did it implement

**Comment by SundeepK** [comment]
@carl1990 I'll be able to get around to it in the coming week I believe.

**Comment by SundeepK** [comment]
I believe I have this done now. Basically you have the set the first day of month using the constance provided in the `Calendar` class. Example usage:

```
compactCalendarView.setFirstDayOfWeek(Calendar.SUNDAY);
```

or in the case of the ticket, you have todo:

```
compactCalendarView.setFirstDayOfWeek(Calendar.THURSDAY);
```

**Comment by SundeepK** [comment]
```
dependencies {
    compile 'com.github.sundeepk:compact-calendar-view:1.9.7'
}
```

Should be in 1.9.7 please allow some time for it to be available.

**Comment by OliverMannhart** [comment]
Hey there,

I have tested it and it works great!
Thanks a lot for your work during the holidays. 
I really appreciate it.
