### ISSUE TITLE
Support custom Timezone

### ISSUE THREAD

**Issue by schmidan** [SundeepK/CompactCalendarView#95]
at the moment the widget uses the default TimeZone

```
        this.currentCalender = Calendar.getInstance(locale);
        this.todayCalender = Calendar.getInstance(locale);
        this.calendarWithFirstDayOfMonth = Calendar.getInstance(locale);
        this.eventsCalendar = Calendar.getInstance(locale);
```

We would need a way to customise those calendars with a different TimeZone than the current system TimeZone.

Is this something you would implement?

**Comment by SundeepK** [comment]
Seems like simple enough. When setting the locale, give the option to set the timezone as well as perhaps a method override.

**Comment by SundeepK** [comment]
I've modified the `setLocale` method to allow you to set the locale and timezon. Will release a new version today.

**Comment by SundeepK** [comment]
Should be released under:
```
dependencies {
    compile 'com.github.sundeepk:compact-calendar-view:1.9.0'
}
```

However, I think the best way to get date in a specific timezone is to use `SimpleDateFormat` by setting the time zone on that. Which makes the most sense.

**Comment by SundeepK** [comment]
Closing this issue.

**Comment by schmidan** [comment]
The app (www.teamup.com) in which we use your lib allows switching of timezones depending on which cloud shared calendar the user looks at.

the solution you provided with 1.9.0 works perfectly thank you!
