### ISSUE TITLE
How can i add an event on a particular date.

### ISSUE THREAD

**Issue by Frankenstein666** [SundeepK/CompactCalendarView#96]
How can i add an event on a particular date, i can't understand the  example, i am getting date data from json in YYYY-mm-dd hh:mm format, how do i display this data in calendar.

**Comment by SundeepK** [comment]
Hi, adding events should be simple. First you need to convert the date string you have in `YYYY-mm-dd hh:mm` format to a date object instance. You can do this using `SimpleDateFormat` class in java. Once you have the date, you can add an event like so:

```java
  String date = "2016-01-01 00:00";
  SimpleDateFormat sdt  = new SimpleDateFormat("YYYY-mm-dd hh:mm", Locale.getDefault());
  Event ev1 new Event(Color.GREEN, sdf.parse(date).getTime());
  compactCalendar.addEvent(ev1);
```

**Comment by Frankenstein666** [comment]
Thanks for  the reply that really helped, again i want to ask more thing, i have a list of events below the compactCalendarview, how do i update the listview as the current month is swiped by user.
do i handle it in onMonthScroll method?

**Comment by SundeepK** [comment]
yes thats correct, when ever the calendar is scrolled, you will get a callback so that way you can update your listview however you need too.

**Comment by SundeepK** [comment]
Will close this issue. You can reopen if you need more help.

**Comment by ghost** [comment]
Hi, could you give more details how to add an event?
