### ISSUE TITLE
How can disable scroll month

### ISSUE THREAD

**Issue by xiaotianyilang** [SundeepK/CompactCalendarView#98]
when i do it like this: compactCalendarView.shouldScrollMonth(false); however, it does't work! what should i do?

**Comment by SundeepK** [comment]
I think you descovered a bug, looks like a pul request that was merged recently caused this to break and there was no test for it. Good news is its a one line change and add a test for this as well.

**Comment by SundeepK** [comment]
I believe I fixed the bug, will try and release a new verion today.

**Comment by SundeepK** [comment]
Should be available soon in version(may take some time):
```
dependencies {
    compile 'com.github.sundeepk:compact-calendar-view:1.8.9'
}
```
