### ISSUE TITLE
How to change the title of the adapter (Default: "home") to the month of the calendar

### ISSUE THREAD

**Issue by VirtueDnS** [SundeepK/CompactCalendarView#99]

**Comment by SundeepK** [comment]
Hi, you need to get the toolbar and set the title. If you have a look at the sample app, it shows exactly how to do this.

**Comment by VirtueDnS** [comment]
Sorry, I should say clearly. In fact, I want to change the title of the calendar instead of the toolbar.

**Comment by SundeepK** [comment]
The calendar doesn't have a title - its generic. It's up to you on how to display the month, using the listener.

**Comment by SundeepK** [comment]
Closing this issue, please let me know if you need more help.
